document.body.classList.add('course-mode');

const courseOrder = ['overview','vocabulary','listening','reading','writing','speaking','review','progress'];
const courseMeta = {
  overview:['今日概览','先看清今天的目标，再按顺序完成课程','10 分钟'], vocabulary:['词汇与语法','核心词不是背中文，而是学会在雅思语境中使用','35 分钟'],
  listening:['听力精听','先盲听，再核对文本，最后跟读','40 分钟'], reading:['阅读精读','训练定位、同义替换和证据意识','40 分钟'],
  writing:['写作训练','用清晰结构写出一个完整段落','20 分钟'], speaking:['口语跟练','录音、复听、重说，比默想有效','15 分钟'],
  review:['当日复盘','记录错因和明天唯一的改进点','10 分钟'], progress:['成绩与设置','查看路线、模考成绩、复盘与数据备份','管理中心']
};

const seedWords = [
  ['allocate','/ˈæləkeɪt/','分配；划拨','The government should allocate more funds to public transport.','政府应给公共交通划拨更多资金。'],
  ['beneficial','/ˌbenɪˈfɪʃl/','有益的','Regular exercise is beneficial to both physical and mental health.','规律锻炼对身心健康都有益。'],
  ['consequence','/ˈkɒnsɪkwəns/','结果；后果','Traffic congestion is a consequence of rapid urbanisation.','交通拥堵是快速城市化的结果。'],
  ['considerable','/kənˈsɪdərəbl/','相当大的','The project requires a considerable amount of investment.','该项目需要大量投资。'],
  ['decline','/dɪˈklaɪn/','下降；衰退','The chart shows a gradual decline in car ownership.','图表显示汽车拥有量逐渐下降。'],
  ['efficient','/ɪˈfɪʃnt/','高效的','Rail travel is often more efficient than driving.','铁路出行通常比驾车更高效。'],
  ['essential','/ɪˈsenʃl/','必不可少的','Access to clean water is essential for public health.','获得清洁水对公共健康至关重要。'],
  ['factor','/ˈfæktə/','因素','Cost is an important factor when people choose a home.','成本是人们选择住房时的重要因素。'],
  ['implement','/ˈɪmplɪment/','实施','Schools should implement practical environmental programmes.','学校应实施实用的环保项目。'],
  ['indicate','/ˈɪndɪkeɪt/','表明；显示','The figures indicate a change in consumer behaviour.','这些数据表明消费者行为发生了变化。'],
  ['maintain','/meɪnˈteɪn/','维持；维护','Cities must maintain reliable public services.','城市必须维持可靠的公共服务。'],
  ['majority','/məˈdʒɒrəti/','大多数','The majority of participants preferred flexible working hours.','大多数参与者更喜欢弹性工作时间。'],
  ['significant','/sɪɡˈnɪfɪkənt/','显著的；重要的','There was a significant increase in online shopping.','网络购物显著增长。'],
  ['sustainable','/səˈsteɪnəbl/','可持续的','Governments need to invest in sustainable energy.','政府需要投资可持续能源。'],
  ['tendency','/ˈtendənsi/','趋势；倾向','There is a tendency for young adults to delay marriage.','年轻人有推迟结婚的趋势。'],
  ['urban','/ˈɜːbən/','城市的','Urban areas offer more employment opportunities.','城市地区提供更多就业机会。'],
  ['vary','/ˈveəri/','变化；不同','Housing costs vary considerably between regions.','各地区住房成本差异很大。'],
  ['whereas','/ˌweərˈæz/','然而；而','Car use rose, whereas bus travel declined.','汽车使用增加，而公交出行下降。'],
  ['widespread','/ˈwaɪdspred/','广泛的','Smartphone use is widespread among all age groups.','智能手机在所有年龄群体中广泛使用。'],
  ['priority','/praɪˈɒrəti/','优先事项','Improving air quality should be a national priority.','改善空气质量应成为国家优先事项。']
];
let wordBank = [];
let activeWords = [];
function esc(value){ const node=document.createElement('span'); node.textContent=String(value??''); return node.innerHTML; }
function normalizeWord(w){ return Array.isArray(w) ? {word:w[0],phonetic:w[1],meaning:w[2],definition_en:w[2],example_sentence:w[3],example_zh:w[4],theme:'IELTS Core',difficulty:3,pos:''} : {...w,meaning:w.definition_en,phonetic:'',example_zh:''}; }
function allWords(){ return wordBank.length ? wordBank.map(normalizeWord) : seedWords.map(normalizeWord); }
function dailyWords(){ const pool=allWords(), start=((studyDay()-1)*20)%pool.length; return Array.from({length:Math.min(20,pool.length)},(_,i)=>pool[(start+i)%pool.length]); }
function wordCard(w,i){ const mastered=(state.masteredWords||[]).includes(w.word); return `<button class="word-card ${mastered?'mastered':''}" data-word="${i}" aria-expanded="false"><strong>${esc(w.word)}</strong>${w.phonetic?`<span class="phonetic">${esc(w.phonetic)}</span>`:''}<span>${w.pos?`${esc(w.pos)} · `:''}${esc(w.meaning)}</span>${mastered?'<small>已掌握</small>':''}</button>`; }

function courseState(){ state.courseCompleted = state.courseCompleted || {}; state.courseCompleted[todayKey()] = state.courseCompleted[todayKey()] || {}; return state.courseCompleted[todayKey()]; }
function isDone(route){ return Boolean(courseState()[route]); }
function markDone(route){ courseState()[route] = true; saveState(); updateCourseNav(); showToast(`${courseMeta[route][0]}已完成，继续下一项。`); }
function header(route){ const m=courseMeta[route]; return `<div class="lesson-head"><div><p class="eyebrow">DAY ${studyDay()} · IELTS 7 COURSE</p><h2 id="lessonTitle">${m[0]}</h2><p>${m[1]}</p></div><span class="lesson-badge">${m[2]}</span></div>`; }
function footer(route){ const i=courseOrder.indexOf(route), prev=courseOrder[Math.max(0,i-1)], next=courseOrder[Math.min(courseOrder.length-1,i+1)]; return `<div class="lesson-footer"><button data-route-link="${prev}">← 上一项</button>${route!=='progress'?`<button class="next" data-complete="${route}" data-next="${next}">${isDone(route)?'已完成 · 继续下一项':'完成并进入下一项 →'}</button>`:''}</div>`; }

function overviewView(){ const lessons=courseOrder.slice(1,7); return `${header('overview')}<div class="lesson-grid"><section class="lesson-main"><h3>今天按这个顺序学习</h3><div class="course-sequence">${lessons.map((r,i)=>`<button class="sequence-button" data-route-link="${r}"><span class="order-dot">${i+1}</span><span><strong>${courseMeta[r][0]}</strong><small>${courseMeta[r][1]}</small></span><span class="status">${isDone(r)?'已完成':courseMeta[r][2]}</span></button>`).join('')}</div></section><aside class="lesson-aside"><h3>今天的完成标准</h3><ul class="instruction-list"><li>20 个词至少能认出 16 个</li><li>听力能解释每道错题的原因</li><li>阅读答案必须有原文证据</li><li>写作完成一个结构清晰的段落</li><li>口语录音至少重说一次</li></ul><p class="plan-advice">不要同时打开多个课程。完成一项，再进入下一项。</p></aside></div>${footer('overview')}`; }
function vocabularyView(){ activeWords=dailyWords(); const themes=[...new Set(allWords().map(w=>w.theme).filter(Boolean))].sort(); return `${header('vocabulary')}<div class="lesson-grid"><section class="lesson-main"><div class="word-bank-head"><div><h3>今日 20 词 · 第 ${studyDay()} 天</h3><p>完整词库 ${allWords().length} 词；今日词汇按日期自动轮换。</p></div><div class="mastery-count">已掌握 ${(state.masteredWords||[]).length} / ${allWords().length}</div></div><div class="word-filters"><label>搜索全部词库<input id="wordSearch" type="search" placeholder="输入单词、定义或主题"></label><label>主题<select id="wordTheme"><option value="">全部主题</option>${themes.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></label><label>难度<select id="wordDifficulty"><option value="">全部</option><option value="3">3 · 中级</option><option value="4">4 · 中高级</option><option value="5">5 · 高级</option></select></label><button class="mini-button" id="showDailyWords">今日 20 词</button></div><p id="wordResultCount" class="word-result-count">显示今日 20 词</p><div id="wordDetail" class="word-detail view-hidden"></div><div class="word-grid" id="wordGrid">${activeWords.map(wordCard).join('')}</div><div class="exercise"><h3>语法重点：比较与对比</h3><p><strong>whereas / while</strong> 连接两个相反趋势：<br><em>Car use increased, whereas bus travel declined.</em></p><label>仿写一句对比句<input id="grammarAnswer" type="text" placeholder="Online sales rose, whereas ..."></label><div class="feedback" id="grammarFeedback"></div><button class="mini-button" data-check-grammar>检查句子</button></div>${footer('vocabulary')}</section><aside class="lesson-aside"><h3>词库学习方法</h3><ol class="instruction-list"><li>每天先学系统安排的 20 词</li><li>点击单词阅读定义、同义词和例句</li><li>会用后再标记“已掌握”</li><li>搜索可访问全部 1,000 词</li></ol><p class="plan-advice">50 天完成一轮新词；后续按未掌握词循环复习。</p><p class="source-note">词库来源：<a href="https://wordlevel.net" target="_blank" rel="noopener">WordLevel</a>，MIT License。</p></aside></div>`; }
function listeningView(){ return `${header('listening')}<div class="lesson-grid"><section class="lesson-main"><div class="prompt-box"><strong>场景：预订社区课程</strong><br>目标：数字、日期、拼写和同义替换</div><h3>第一遍：只听信息结构</h3><p>使用浏览器朗读下面的英文。第一遍不要看文本，记下人物、目的和三个关键信息。</p><button class="mini-button" data-speak-listening>▶ 播放听力文本</button><details class="exercise"><summary>完成盲听后展开文本</summary><div class="transcript">Good morning, Westfield Community Centre. — Hello, I'd like to enrol in the <span class="keyword">beginner photography course</span>. — Certainly. It starts on <span class="keyword">the fifteenth of September</span> and runs for six weeks. Classes are held on <span class="keyword">Thursday evenings</span> from six thirty to eight. The total fee is <span class="keyword">ninety-five pounds</span>, including materials.</div></details><div class="exercise"><h3>听力检查</h3>${[['课程名称是什么？','beginner photography'],['开课日期？','15 September'],['总费用？','95 pounds']].map((q,i)=>`<label>${i+1}. ${q[0]}<input type="text" data-listening-answer="${q[1]}"></label>`).join('')}<button class="mini-button" data-check-listening>核对答案</button><div class="feedback" id="listeningFeedback"></div></div>${footer('listening')}</section><aside class="lesson-aside"><h3>精听四步</h3><ol class="instruction-list"><li>盲听一遍抓场景</li><li>第二遍填写答案</li><li>展开文本定位漏听处</li><li>跟读三遍，模仿重音</li></ol><p class="plan-advice">错题分类：没听见 / 听见没反应 / 拼写错误。</p></aside></div>`; }
function readingView(){ return `${header('reading')}<div class="lesson-grid"><section class="lesson-main"><p class="eyebrow">PASSAGE · URBAN TRANSPORT</p><h3>Why cities are rethinking private cars</h3><div class="transcript"><p>For much of the twentieth century, urban planning gave priority to private vehicles. Wider roads were expected to reduce congestion. However, researchers found that additional road capacity often encouraged more people to drive, so traffic soon returned to previous levels.</p><p>Many cities are now allocating street space to buses, bicycles and pedestrians. Although these policies can initially face public opposition, evidence indicates that reliable alternatives reduce car dependence over time. The most successful programmes combine restrictions with affordable public transport rather than simply making driving more difficult.</p><p>Environmental benefits are significant, but they are not the only reason for change. Streets with less traffic tend to be safer, quieter and more beneficial to local businesses because people spend more time in the area.</p></div><div class="exercise"><h3>判断题：True / False / Not Given</h3>${[['Building wider roads permanently solved congestion.','False'],['Successful transport policies only restrict driving.','False'],['Every local business supports reducing traffic.','Not Given']].map((q,i)=>`<div class="question"><p>${i+1}. ${q[0]}</p>${['True','False','Not Given'].map(o=>`<label><input type="radio" name="rq${i}" value="${o}" data-correct="${q[1]}">${o}</label>`).join('')}</div>`).join('')}<button class="mini-button" data-check-reading>核对并查看证据</button><div class="feedback" id="readingFeedback"></div></div>${footer('reading')}</section><aside class="lesson-aside"><h3>判断题原则</h3><ul class="instruction-list"><li>True：原文明确同义表达</li><li>False：原文明确相反</li><li>Not Given：原文没有足够信息</li></ul><p class="plan-advice">不要用常识判断。答案只来自文章。</p></aside></div>`; }
function writingView(){ return `${header('writing')}<div class="lesson-grid"><section class="lesson-main"><div class="prompt-box"><strong>Task 2 练习</strong><br>Some people think governments should invest more in public transport than in building new roads. To what extent do you agree or disagree?</div><div class="writing-frame"><div><strong>观点句</strong><span>直接回答题目</span></div><div><strong>原因</strong><span>解释为什么</span></div><div><strong>例子</strong><span>具体场景或结果</span></div><div><strong>回扣</strong><span>连接中心观点</span></div></div><label>写一个 80–110 词主体段<textarea id="writingDraft" rows="9" placeholder="Investing in public transport is a more sustainable solution because..."></textarea></label><div class="feedback" id="wordCount">0 词</div><div class="course-card"><h3>自检清单</h3><label><input type="checkbox"> 第一单句表达清晰观点</label><br><label><input type="checkbox"> 每个观点都有解释或例子</label><br><label><input type="checkbox"> 使用 whereas / because / therefore 中至少两个</label></div>${footer('writing')}</section><aside class="lesson-aside"><h3>参考思路</h3><ul class="instruction-list"><li>公共交通承载更多乘客</li><li>减少拥堵与空气污染</li><li>道路扩建可能诱发更多车流</li><li>低收入群体也能受益</li></ul><p>不要背整篇范文。先把一个段落写清楚。</p></aside></div>`; }
function speakingView(){ return `${header('speaking')}<div class="lesson-grid"><section class="lesson-main"><div class="speaking-card"><p class="eyebrow">PART 1</p><h3>Do you often use public transport?</h3><p>回答结构：直接回答 + 原因 + 一个具体细节。目标 20–30 秒。</p></div><div class="speaking-card"><p class="eyebrow">PART 2</p><h3>Describe a journey you remember well.</h3><p>You should say: where you went; who you travelled with; what happened; and explain why you remember it.</p></div><div class="record-timer" id="speakTimer">01:00</div><button class="complete-lesson" data-speaking-timer>开始 1 分钟准备</button><div class="exercise"><label>录音后写下一个需要修正的问题<input id="speakingNote" type="text" placeholder="例如：停顿太多；反复使用 very"></label></div>${footer('speaking')}</section><aside class="lesson-aside"><h3>口语评分关注</h3><ul class="instruction-list"><li>流利与连贯</li><li>词汇范围与准确性</li><li>语法多样性与准确性</li><li>发音清晰度</li></ul><p class="plan-advice">不要追求口音。目标是清楚、自然、持续表达。</p></aside></div>`; }
function reviewView(){ return `${header('review')}<div class="lesson-grid"><section class="lesson-main"><h3>完成今天的闭环</h3><div class="review-checks">${['我复习了今天的核心词汇','我能解释听力错题为什么错','阅读答案都有原文证据','写作完成了一个完整段落','口语至少录音并重说一次'].map(x=>`<label><input type="checkbox" data-review-check>${x}</label>`).join('')}</div><div class="exercise"><label>今天最重要的收获<textarea id="dailyWin" rows="3"></textarea></label><label>明天只改进一件事<input id="tomorrowFocus" type="text"></label></div>${footer('review')}</section><aside class="lesson-aside"><h3>完成情况</h3><div class="record-timer" id="dayCompletion">0%</div><p>复盘不是重抄错题。只记：我为什么错、下次看到什么信号要改变做法。</p></aside></div>`; }
function progressView(){ const scores=[...(state.scores||[])].reverse().slice(0,5); return `${header('progress')}<div class="lesson-grid"><section class="lesson-main"><h3>备考设置</h3><form id="courseSettings" class="review-form"><label>计划开始日期<input id="courseStart" type="date" value="${state.startDate}"></label><label>预计考试日期<input id="courseExam" type="date" value="${state.examDate||''}"></label><label>每日学习时长<select id="courseMinutes"><option value="120" ${state.dailyMinutes===120?'selected':''}>2 小时</option><option value="150" ${state.dailyMinutes===150?'selected':''}>2.5 小时</option><option value="180" ${state.dailyMinutes===180?'selected':''}>3 小时</option></select></label><label>当前最弱项<select id="courseWeak"><option value="">尚未确定</option>${[['listening','听力'],['reading','阅读'],['writing','写作'],['speaking','口语']].map(x=>`<option value="${x[0]}" ${state.weakSkill===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><button class="primary-button" type="submit">保存备考设置</button></form><div class="exercise"><h3>最近模考</h3>${scores.length?scores.map(s=>`<div class="score-row"><time>${s.date}</time><span>听 ${s.l}</span><span>读 ${s.r}</span><span>写 ${s.w}</span><span>说 ${s.s}</span><strong>${s.overall.toFixed(1)}</strong></div>`).join(''):'<p class="empty">尚未记录模考成绩。完成第一次基线测试后，可在原始仪表盘中录入。</p>'}</div><div class="exercise"><h3>四阶段路线</h3><div class="resource-list">${phases.map((p,i)=>`<div class="resource-item"><strong>${i+1}. ${p.title} · 第 ${p.start}–${p.end} 天</strong><span>${p.goal}；${p.target}</span></div>`).join('')}</div></div></section><aside class="lesson-aside"><h3>完整备考资料</h3><div class="resource-list"><div class="resource-item"><strong>真题主线</strong><span>剑桥雅思 12–19，按阶段从单篇到整套</span></div><div class="resource-item"><strong>词汇</strong><span>按主题学习搭配与例句，不孤立背单词</span></div><div class="resource-item"><strong>写作</strong><span>Task 1 图表语言 + Task 2 观点论证</span></div><div class="resource-item"><strong>口语</strong><span>Part 1 短答、Part 2 叙述、Part 3 深入讨论</span></div></div></aside></div>${footer('progress')}`; }

const views={overview:overviewView,vocabulary:vocabularyView,listening:listeningView,reading:readingView,writing:writingView,speaking:speakingView,review:reviewView,progress:progressView};
function navigate(route,push=true){ if(!views[route]) route='overview'; document.getElementById('lessonApp').innerHTML=views[route](); document.querySelectorAll('.course-nav .nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); if(push) history.replaceState(null,'',`#course-${route}`); bindView(route); document.getElementById('lessonApp').focus({preventScroll:true}); window.scrollTo({top:0,behavior:'smooth'}); }
function updateCourseNav(){ document.querySelectorAll('.course-nav [data-route]').forEach(b=>{ const done=isDone(b.dataset.route); b.classList.toggle('completed',done); const small=b.querySelector('small'); if(done&&small) small.textContent='已完成'; }); }
function speak(text,rate=.85){ if(!('speechSynthesis' in window)){showToast('当前浏览器不支持语音朗读。');return;} speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='en-GB';u.rate=rate;speechSynthesis.speak(u); }
function attachWordListeners(){
  document.querySelectorAll('[data-word]').forEach(b=>b.addEventListener('click',()=>{const w=activeWords[Number(b.dataset.word)], box=document.getElementById('wordDetail');document.querySelectorAll('[data-word]').forEach(x=>x.setAttribute('aria-expanded','false'));b.setAttribute('aria-expanded','true');box.classList.remove('view-hidden');const mastered=(state.masteredWords||[]).includes(w.word);box.innerHTML=`<h3>${esc(w.word)} ${w.phonetic?`<span class="phonetic">${esc(w.phonetic)}</span>`:''}</h3><p><strong>${esc(w.pos||'word')}</strong> · 难度 ${esc(w.difficulty||3)}/5 · ${esc(w.theme||'Academic')}</p><p class="meaning">${esc(w.meaning)}</p>${w.synonyms?.length?`<p><strong>同义词：</strong>${w.synonyms.map(esc).join(', ')}</p>`:''}<p class="example">${esc(w.example_sentence||'')}${w.example_zh?`<br>${esc(w.example_zh)}`:''}</p><div class="word-actions"><button class="mini-button" data-say-word>朗读单词</button><button class="mini-button" data-say-example>朗读例句</button><button class="mini-button" data-master-word>${mastered?'取消已掌握':'标记已掌握'}</button></div>`;box.querySelector('[data-say-word]').onclick=()=>speak(w.word,.75);box.querySelector('[data-say-example]').onclick=()=>speak(w.example_sentence,.82);box.querySelector('[data-master-word]').onclick=()=>{const set=new Set(state.masteredWords||[]);set.has(w.word)?set.delete(w.word):set.add(w.word);state.masteredWords=[...set];saveState();navigate('vocabulary',false);showToast(set.has(w.word)?'已加入掌握词汇。':'已移回待学习词汇。');};box.scrollIntoView({behavior:'smooth',block:'nearest'});}));
}
function renderWordResults(useDaily=false){ const grid=document.getElementById('wordGrid'); if(!grid)return; if(useDaily){activeWords=dailyWords();document.getElementById('wordSearch').value='';document.getElementById('wordTheme').value='';document.getElementById('wordDifficulty').value='';}else{const q=document.getElementById('wordSearch').value.trim().toLowerCase(),theme=document.getElementById('wordTheme').value,difficulty=document.getElementById('wordDifficulty').value;activeWords=allWords().filter(w=>(!q||`${w.word} ${w.meaning} ${w.theme} ${(w.synonyms||[]).join(' ')}`.toLowerCase().includes(q))&&(!theme||w.theme===theme)&&(!difficulty||String(w.difficulty)===difficulty)).slice(0,100);} grid.innerHTML=activeWords.map(wordCard).join('')||'<p class="empty">没有匹配结果，请调整搜索条件。</p>';document.getElementById('wordResultCount').textContent=useDaily?'显示今日 20 词':`找到 ${activeWords.length}${activeWords.length===100?'（最多显示前 100 条）':''}`;document.getElementById('wordDetail').classList.add('view-hidden');attachWordListeners(); }
function bindView(route){
  document.querySelectorAll('[data-route-link]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.routeLink)));
  document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>{markDone(b.dataset.complete);navigate(b.dataset.next)}));
  attachWordListeners();
  document.getElementById('wordSearch')?.addEventListener('input',()=>renderWordResults(false));
  document.getElementById('wordTheme')?.addEventListener('change',()=>renderWordResults(false));
  document.getElementById('wordDifficulty')?.addEventListener('change',()=>renderWordResults(false));
  document.getElementById('showDailyWords')?.addEventListener('click',()=>renderWordResults(true));
  document.querySelector('[data-check-grammar]')?.addEventListener('click',()=>{const v=document.getElementById('grammarAnswer').value.trim();document.getElementById('grammarFeedback').textContent=v.length>18&&/whereas|while/i.test(v)?'结构正确。再检查主谓和时态。':'请写一个完整句，并使用 whereas 或 while。';});
  document.querySelector('[data-speak-listening]')?.addEventListener('click',()=>speak("Good morning, Westfield Community Centre. Hello, I'd like to enrol in the beginner photography course. Certainly. It starts on the fifteenth of September and runs for six weeks. Classes are held on Thursday evenings from six thirty to eight. The total fee is ninety-five pounds, including materials.",.78));
  document.querySelector('[data-check-listening]')?.addEventListener('click',()=>{let n=0;document.querySelectorAll('[data-listening-answer]').forEach(x=>{if(x.value.toLowerCase().includes(x.dataset.listeningAnswer.toLowerCase()))n++});document.getElementById('listeningFeedback').textContent=`答对 ${n}/3。错误项请回到文本定位原句并跟读。`;});
  document.querySelector('[data-check-reading]')?.addEventListener('click',()=>{let n=0;document.querySelectorAll('.question').forEach(q=>{const x=q.querySelector('input:checked');if(x&&x.value===x.dataset.correct)n++});document.getElementById('readingFeedback').textContent=`答对 ${n}/3。证据依次在第 1 段末、第 2 段末；第 3 题原文没有说明“所有商家”。`;});
  document.getElementById('writingDraft')?.addEventListener('input',e=>{const n=e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0;document.getElementById('wordCount').textContent=`${n} 词 · 目标 80–110 词`;state.drafts=state.drafts||{};state.drafts.writing=e.target.value;saveState();});
  if(document.getElementById('writingDraft')&&state.drafts?.writing){document.getElementById('writingDraft').value=state.drafts.writing;document.getElementById('writingDraft').dispatchEvent(new Event('input'));}
  document.querySelector('[data-speaking-timer]')?.addEventListener('click',e=>{let left=60;e.target.disabled=true;const el=document.getElementById('speakTimer'),iv=setInterval(()=>{left--;el.textContent=`00:${String(left).padStart(2,'0')}`;if(left<=0){clearInterval(iv);e.target.disabled=false;e.target.textContent='开始 2 分钟作答';el.textContent='02:00';showToast('准备结束，现在开始作答并录音。');}},1000);});
  document.querySelectorAll('[data-review-check]').forEach(x=>x.addEventListener('change',()=>{const all=[...document.querySelectorAll('[data-review-check]')],n=all.filter(x=>x.checked).length;document.getElementById('dayCompletion').textContent=`${Math.round(n/all.length*100)}%`;}));
  document.getElementById('courseSettings')?.addEventListener('submit',e=>{e.preventDefault();state.startDate=document.getElementById('courseStart').value;state.examDate=document.getElementById('courseExam').value;state.dailyMinutes=Number(document.getElementById('courseMinutes').value);state.weakSkill=document.getElementById('courseWeak').value;saveState();showToast('备考设置已保存。');render();});
  updateCourseNav();
}

document.querySelectorAll('.course-nav [data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));
const initial=location.hash.startsWith('#course-')?location.hash.replace('#course-',''):'overview';
navigate(initial,false);
fetch('./data/ielts-core-1000.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(words=>{wordBank=words;if(location.hash==='#course-vocabulary')navigate('vocabulary',false);}).catch(()=>showToast('完整词库加载失败，已切换到内置核心词。'));
