document.body.classList.add('course-mode');

const courseOrder = ['overview','vocabulary','listening','reading','writing','speaking','practical','review','progress'];
const courseMeta = {
  overview:['今日概览','先看清今天的目标，再按顺序完成课程','10 分钟'], vocabulary:['词汇与语法','核心词不是背中文，而是学会在雅思语境中使用','35 分钟'],
  listening:['听力精听','先盲听，再核对文本，最后跟读','40 分钟'], reading:['阅读精读','训练定位、同义替换和证据意识','40 分钟'],
  writing:['写作训练','用清晰结构写出一个完整段落','20 分钟'], speaking:['口语跟练','录音、复听、重说，比默想有效','15 分钟'],
  practical:['应用英语','把今天学到的英语带进真实的海外场景','20 分钟'],
  review:['当日复盘','记录错因和明天唯一的改进点','10 分钟'], progress:['成绩与设置','查看路线、模考成绩、复盘与数据备份','管理中心']
};

const practicalTracks = [
  {key:'life',title:'Real-world English',label:'海外生活',scenes:['租房咨询与看房','银行开户与转账','电话预约与确认','描述症状与医疗问诊','退换货与消费者沟通','公共交通问路与延误','政府机构办事','邻里与日常社交'],phrases:['Could you walk me through the process?','Could you clarify whether this is included?','I would like to confirm the details before proceeding.']},
  {key:'study',title:'Study Abroad English',label:'海外学习',scenes:['听 Lecture 并记笔记','阅读 Academic Paper','Seminar 表达与追问','课堂 Presentation','Academic Essay','Email Professor','Group Project 协作'],phrases:['The main point I took from this is…','Could you elaborate on that point?','I agree to some extent; however, the evidence suggests…']},
  {key:'career',title:'Career English',label:'海外求职与职场',scenes:['English CV','Cover Letter','LinkedIn 个人简介','Self Introduction','Behavioral Interview','Professional Interview','Workplace Communication','Meeting 发言','Professional Email','Presentation'],phrases:['My experience is particularly relevant because…','The situation required me to…','To make sure we are aligned, the next step is…']}
];

function daysToExam(){ if(!state.examDate)return null; const end=new Date(`${state.examDate}T00:00:00`),now=new Date();now.setHours(0,0,0,0);return Math.max(0,Math.ceil((end-now)/86400000)); }
function learningMix(){ const left=daysToExam(); if(left!==null&&left<=60)return {ielts:90,life:4,study:3,career:3,label:'考前冲刺'}; if(left!==null&&left<=120)return {ielts:82,life:6,study:6,career:6,label:'考试强化'}; if(studyDay()>140)return {ielts:90,life:4,study:3,career:3,label:'套题冲刺'}; if(studyDay()>84)return {ielts:82,life:6,study:6,career:6,label:'能力提分'}; return {ielts:70,life:10,study:10,career:10,label:'基础与真实应用并行'}; }
function todaysPractical(){ const day=studyDay()-1,track=practicalTracks[day%practicalTracks.length],scene=track.scenes[Math.floor(day/practicalTracks.length)%track.scenes.length];return {track,scene}; }

const seedWords = [
  ['allocate','/ˈæləkeɪt/','分配；划拨','The government should allocate more funds to public transport.','政府应给公共交通划拨更多资金。'],
  ['beneficial','/ˌbenɪˈfɪʃl/','有益的','Regular exercise is beneficial to both physical and mental health.','规律锻炼对身心健康都有益。'],
  ['consequence','/ˈkɒnsɪkwəns/','结果；后果','Traffic congestion is a consequence of rapid urbanisation.','交通拥堵是快速城市化的结果。'],
  ['considerable','/kənˈsɪdərəbl/','相当大的','The project requires a considerable amount of investment.','该项目需要大量投资。'],
  ['decline','/dɪˈklaɪn/','下降；衰退','The chart shows a gradual decline in car ownership.','图表显示汽车拥有量逐渐下降。'],
  ['efficient','/ɪˈfɪʃnt/','高效的','Rail travel is often more efficient than driving.','铁路出行通常比驾车更高效。'],
  ['essential','/ɪˈsenʃl/','必不可少的','Access to clean water is essential for public health.','获得清洁水对公共健康至关重要。'],
  ['factor','/ˈfæktə/','因素','Cost is an important factor when people choose a home.','成本是人们选择住房时的重要因素。'],
  ['implement','/ˈɪmplɪment/','实施','Schools should implement practical environmental programmes.','学校应实施实用的环保项目。'],
  ['indicate','/ˈɪndɪkeɪt/','表明；显示','The figures indicate a change in consumer behaviour.','这些数据表明消费者行为发生了变化。'],
  ['maintain','/meɪnˈteɪn/','维持；维护','Cities must maintain reliable public services.','城市必须维持可靠的公共服务。'],
  ['majority','/məˈdʒɒrəti/','大多数','The majority of participants preferred flexible working hours.','大多数参与者更喜欢弹性工作时间。'],
  ['significant','/sɪɡˈnɪfɪkənt/','显著的；重要的','There was a significant increase in online shopping.','网络购物显著增长。'],
  ['sustainable','/səˈsteɪnəbl/','可持续的','Governments need to invest in sustainable energy.','政府需要投资可持续能源。'],
  ['tendency','/ˈtendənsi/','趋势；倾向','There is a tendency for young adults to delay marriage.','年轻人有推迟结婚的趋势。'],
  ['urban','/ˈɜːbən/','城市的','Urban areas offer more employment opportunities.','城市地区提供更多就业机会。'],
  ['vary','/ˈveəri/','变化；不同','Housing costs vary considerably between regions.','各地区住房成本差异很大。'],
  ['whereas','/ˌweərˈæz/','然而；而','Car use rose, whereas bus travel declined.','汽车使用增加，而公交出行下降。'],
  ['widespread','/ˈwaɪdspred/','广泛的','Smartphone use is widespread among all age groups.','智能手机在所有年龄群体中广泛使用。'],
  ['priority','/praɪˈɒrəti/','优先事项','Improving air quality should be a national priority.','改善空气质量应成为国家优先事项。']
];
let wordBank = [];
let cefrBank = [];
let selectedWordBank = 'academic';
let activeWords = [];
function esc(value){ const node=document.createElement('span'); node.textContent=String(value??''); return node.innerHTML; }
function normalizeWord(w){ return Array.isArray(w) ? {word:w[0],phonetic:w[1],meaning:w[2],definition_en:w[2],example_sentence:w[3],example_zh:w[4],theme:'IELTS Core',difficulty:3,pos:''} : {...w,meaning:w.definition_en||w.meaning||`${w.cefr||'CEFR'} 识别词汇`,phonetic:w.phonetic||'',example_zh:w.example_zh||''}; }
function academicWords(){ return wordBank.length ? wordBank.map(normalizeWord) : seedWords.map(normalizeWord); }
function allWords(){ return selectedWordBank==='cefr'&&cefrBank.length ? cefrBank.map(normalizeWord) : academicWords(); }
function dailyWords(){ const pool=academicWords(), start=((studyDay()-1)*20)%pool.length; return Array.from({length:Math.min(20,pool.length)},(_,i)=>pool[(start+i)%pool.length]); }
function parseCefrCsv(text){ const seen=new Set();return text.trim().split(/\r?\n/).slice(1).map(line=>{const [word,pos,cefr]=line.split(';');return {word:word?.trim(),pos:pos?.trim(),cefr:cefr?.trim(),theme:'General English',difficulty:{A1:1,A2:2,B1:3,B2:4,C1:5,C2:5}[cefr?.trim()]||3,meaning:`CEFR ${cefr?.trim()||'—'} · ${pos?.trim()||'word'}`};}).filter(w=>w.word&&!seen.has(w.word.toLowerCase())&&seen.add(w.word.toLowerCase())); }
function parseAdvancedCefrCsv(text){ return text.trim().split(/\r?\n/).slice(1).map(line=>{const [word,pos,cefr]=line.split(',');return {word:word?.trim(),pos:pos?.trim(),cefr:cefr?.trim(),theme:'Advanced English',difficulty:5,meaning:`CEFR ${cefr?.trim()||'C1/C2'} · ${pos?.trim()||'word'}`};}).filter(w=>w.word); }
function mergeCefrWords(...lists){ const merged=new Map();lists.flat().forEach(w=>{const key=w.word.toLowerCase();const current=merged.get(key);if(!current||Number(w.cefr?.slice(1))>Number(current.cefr?.slice(1)))merged.set(key,w);});return [...merged.values()]; }
function dailyCefrWords(){ const pool=cefrBank,start=((studyDay()-1)*50)%Math.max(pool.length,1);return pool.length?Array.from({length:Math.min(50,pool.length)},(_,i)=>pool[(start+i)%pool.length]):[]; }
function wordCard(w,i){ const mastered=(state.masteredWords||[]).includes(w.word); return `<button class="word-card ${mastered?'mastered':''}" data-word="${i}" aria-expanded="false"><strong>${esc(w.word)}</strong>${w.phonetic?`<span class="phonetic">${esc(w.phonetic)}</span>`:''}<span>${w.pos?`${esc(w.pos)} · `:''}${esc(w.meaning)}</span>${mastered?'<small>已掌握</small>':''}</button>`; }

function courseState(){ state.courseCompleted = state.courseCompleted || {}; state.courseCompleted[todayKey()] = state.courseCompleted[todayKey()] || {}; return state.courseCompleted[todayKey()]; }
function isDone(route){ return Boolean(courseState()[route]); }
function markDone(route){ courseState()[route] = true; saveState(); updateCourseNav(); showToast(`${courseMeta[route][0]}已完成，继续下一项。`); }
function header(route){ const m=courseMeta[route]; return `<div class="lesson-head"><div><p class="eyebrow">DAY ${studyDay()} · IELTS 7 COURSE</p><h2 id="lessonTitle">${m[0]}</h2><p>${m[1]}</p></div><span class="lesson-badge">${m[2]}</span></div>`; }
function footer(route){ const i=courseOrder.indexOf(route), prev=courseOrder[Math.max(0,i-1)], next=courseOrder[Math.min(courseOrder.length-1,i+1)]; return `<div class="lesson-footer"><button data-route-link="${prev}">← 上一项</button>${route!=='progress'?`<button class="next" data-complete="${route}" data-next="${next}">${isDone(route)?'已完成 · 继续下一项':'完成并进入下一项 →'}</button>`:''}</div>`; }

function missionPath(){ return `<section class="mission-path" aria-labelledby="missionTitle"><div><p class="eyebrow">LONG-TERM MISSION</p><h3 id="missionTitle">英语不是终点，是进入海外学习与工作的工具</h3></div><ol><li class="current"><strong>IELTS 7.0</strong><span>6 个月第一目标</span></li><li><strong>申请海外学校</strong><span>满足语言门槛</span></li><li><strong>英语完成学习</strong><span>Lecture · Paper · Seminar</span></li><li><strong>英文求职</strong><span>CV · Interview · LinkedIn</span></li><li><strong>海外工作与生活</strong><span>长期发展与融入</span></li></ol></section>`; }
function mixPanel(){ const mix=learningMix(),left=daysToExam();return `<section class="learning-mix" aria-labelledby="mixTitle"><div class="mix-head"><div><p class="eyebrow">TODAY'S BALANCE</p><h3 id="mixTitle">今日训练比例 · ${mix.label}</h3></div><strong>${left===null?'设置考试日期后自动调整':`距考试 ${left} 天`}</strong></div><div class="mix-bar" role="img" aria-label="雅思 ${mix.ielts}%，生活英语 ${mix.life}%，留学英语 ${mix.study}%，职场英语 ${mix.career}%"><span class="mix-ielts" style="width:${mix.ielts}%"></span><span class="mix-life" style="width:${mix.life}%"></span><span class="mix-study" style="width:${mix.study}%"></span><span class="mix-career" style="width:${mix.career}%"></span></div><div class="mix-legend"><span><i class="mix-ielts"></i>IELTS ${mix.ielts}%</span><span><i class="mix-life"></i>生活 ${mix.life}%</span><span><i class="mix-study"></i>留学 ${mix.study}%</span><span><i class="mix-career"></i>职场 ${mix.career}%</span></div><p>考试越近，IELTS 训练比例越高；真实英语不断线，每天至少完成一个可使用的表达任务。</p></section>`; }
function overviewView(){ const lessons=courseOrder.slice(1,8),practical=todaysPractical(); return `${header('overview')}${missionPath()}${mixPanel()}<div class="lesson-grid"><section class="lesson-main"><h3>今天按这个顺序学习</h3><div class="course-sequence">${lessons.map((r,i)=>`<button class="sequence-button" data-route-link="${r}"><span class="order-dot">${i+1}</span><span><strong>${courseMeta[r][0]}</strong><small>${r==='practical'?`${practical.track.label} · ${practical.scene}`:courseMeta[r][1]}</small></span><span class="status">${isDone(r)?'已完成':courseMeta[r][2]}</span></button>`).join('')}</div></section><aside class="lesson-aside"><h3>今天的完成标准</h3><ul class="instruction-list"><li>20 个词至少能认出 16 个</li><li>听力与阅读错题都有证据</li><li>写作完成一个清晰段落</li><li>口语录音后至少重说一次</li><li>在真实场景中说出 3 个完整表达</li></ul><p class="plan-advice">IELTS 提供通行证，应用英语保证你到海外后真正能学习、求职和生活。</p></aside></div>${footer('overview')}`; }
function vocabularyView(){ selectedWordBank='academic';activeWords=dailyWords(); const themes=[...new Set(allWords().map(w=>w.theme).filter(Boolean))].sort(); return `${header('vocabulary')}<div class="lesson-grid"><section class="lesson-main"><div class="word-bank-head"><div><h3>今日 20 词 · 第 ${studyDay()} 天</h3><p>1,000 个雅思学术词深度学习 + ${cefrBank.length||'7,988'} 个 CEFR A1–C2 识别词。</p></div><div class="mastery-count">已掌握 ${(state.masteredWords||[]).length} / ${academicWords().length}</div></div><div class="word-filters"><label>词库<select id="wordBankSelect"><option value="academic">雅思学术精学 · ${academicWords().length}</option><option value="cefr">CEFR 完整识别 · ${cefrBank.length||'加载中'}</option></select></label><label>搜索当前词库<input id="wordSearch" type="search" placeholder="输入单词、定义或主题"></label><label>主题<select id="wordTheme"><option value="">全部主题</option>${themes.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></label><label>难度<select id="wordDifficulty"><option value="">全部</option><option value="1">A1</option><option value="2">A2</option><option value="3">B1 / 中级</option><option value="4">B2 / 中高级</option><option value="5">C1–C2 / 高级</option></select></label><button class="mini-button" id="showDailyWords">今日 20 词</button></div><p id="wordResultCount" class="word-result-count">显示今日 20 个学术精学词</p><div id="wordDetail" class="word-detail view-hidden"></div><div class="word-grid" id="wordGrid">${activeWords.map(wordCard).join('')}</div><div class="exercise"><h3>语法重点：比较与对比</h3><p><strong>whereas / while</strong> 连接两个相反趋势：<br><em>Car use increased, whereas bus travel declined.</em></p><label>仿写一句对比句<input id="grammarAnswer" type="text" placeholder="Online sales rose, whereas ..."></label><div class="feedback" id="grammarFeedback"></div><button class="mini-button" data-check-grammar>检查句子</button></div>${footer('vocabulary')}</section><aside class="lesson-aside"><h3>两层词汇体系</h3><ol class="instruction-list"><li>学术精学层：定义、同义词、例句与输出</li><li>CEFR 识别层：从 A1 到 C2 查漏补缺</li><li>每日 20 词始终来自学术精学层</li><li>识别词不等于会用，重点词需进入输出练习</li></ol><p class="plan-advice">先补齐高频基础，再积累学术表达、主题搭配和真实场景语言。</p><p class="source-note">数据采用 MIT License，来源与授权见项目 ATTRIBUTION。</p></aside></div>`; }
function listeningView(){ return `${header('listening')}<div class="lesson-grid"><section class="lesson-main"><div class="prompt-box"><strong>场景：预订社区课程</strong><br>目标：数字、日期、拼写和同义替换</div><h3>第一遍：只听信息结构</h3><p>使用浏览器朗读下面的英文。第一遍不要看文本，记下人物、目的和三个关键信息。</p><button class="mini-button" data-speak-listening>▶ 播放听力文本</button><details class="exercise"><summary>完成盲听后展开文本</summary><div class="transcript">Good morning, Westfield Community Centre. — Hello, I'd like to enrol in the <span class="keyword">beginner photography course</span>. — Certainly. It starts on <span class="keyword">the fifteenth of September</span> and runs for six weeks. Classes are held on <span class="keyword">Thursday evenings</span> from six thirty to eight. The total fee is <span class="keyword">ninety-five pounds</span>, including materials.</div></details><div class="exercise"><h3>听力检查</h3>${[['课程名称是什么？','beginner photography'],['开课日期？','15 September'],['总费用？','95 pounds']].map((q,i)=>`<label>${i+1}. ${q[0]}<input type="text" data-listening-answer="${q[1]}"></label>`).join('')}<button class="mini-button" data-check-listening>核对答案</button><div class="feedback" id="listeningFeedback"></div></div>${footer('listening')}</section><aside class="lesson-aside"><h3>精听四步</h3><ol class="instruction-list"><li>盲听一遍抓场景</li><li>第二遍填写答案</li><li>展开文本定位漏听处</li><li>跟读三遍，模仿重音</li></ol><p class="plan-advice">错题分类：没听见 / 听见没反应 / 拼写错误。</p></aside></div>`; }
function readingView(){ return `${header('reading')}<div class="lesson-grid"><section class="lesson-main"><p class="eyebrow">PASSAGE · URBAN TRANSPORT</p><h3>Why cities are rethinking private cars</h3><div class="transcript"><p>For much of the twentieth century, urban planning gave priority to private vehicles. Wider roads were expected to reduce congestion. However, researchers found that additional road capacity often encouraged more people to drive, so traffic soon returned to previous levels.</p><p>Many cities are now allocating street space to buses, bicycles and pedestrians. Although these policies can initially face public opposition, evidence indicates that reliable alternatives reduce car dependence over time. The most successful programmes combine restrictions with affordable public transport rather than simply making driving more difficult.</p><p>Environmental benefits are significant, but they are not the only reason for change. Streets with less traffic tend to be safer, quieter and more beneficial to local businesses because people spend more time in the area.</p></div><div class="exercise"><h3>判断题：True / False / Not Given</h3>${[['Building wider roads permanently solved congestion.','False'],['Successful transport policies only restrict driving.','False'],['Every local business supports reducing traffic.','Not Given']].map((q,i)=>`<div class="question"><p>${i+1}. ${q[0]}</p>${['True','False','Not Given'].map(o=>`<label><input type="radio" name="rq${i}" value="${o}" data-correct="${q[1]}">${o}</label>`).join('')}</div>`).join('')}<button class="mini-button" data-check-reading>核对并查看证据</button><div class="feedback" id="readingFeedback"></div></div>${footer('reading')}</section><aside class="lesson-aside"><h3>判断题原则</h3><ul class="instruction-list"><li>True：原文明确同义表达</li><li>False：原文明确相反</li><li>Not Given：原文没有足够信息</li></ul><p class="plan-advice">不要用常识判断。答案只来自文章。</p></aside></div>`; }
function writingView(){ return `${header('writing')}<div class="lesson-grid"><section class="lesson-main"><div class="prompt-box"><strong>Task 2 练习</strong><br>Some people think governments should invest more in public transport than in building new roads. To what extent do you agree or disagree?</div><div class="writing-frame"><div><strong>观点句</strong><span>直接回答题目</span></div><div><strong>原因</strong><span>解释为什么</span></div><div><strong>例子</strong><span>具体场景或结果</span></div><div><strong>回扣</strong><span>连接中心观点</span></div></div><label>写一个 80–110 词主体段<textarea id="writingDraft" rows="9" placeholder="Investing in public transport is a more sustainable solution because..."></textarea></label><div class="feedback" id="wordCount">0 词</div><div class="course-card"><h3>自检清单</h3><label><input type="checkbox"> 第一单句表达清晰观点</label><br><label><input type="checkbox"> 每个观点都有解释或例子</label><br><label><input type="checkbox"> 使用 whereas / because / therefore 中至少两个</label></div>${footer('writing')}</section><aside class="lesson-aside"><h3>参考思路</h3><ul class="instruction-list"><li>公共交通承载更多乘客</li><li>减少拥堵与空气污染</li><li>道路扩建可能诱发更多车流</li><li>低收入群体也能受益</li></ul><p>不要背整篇范文。先把一个段落写清楚。</p></aside></div>`; }
function speakingView(){ return `${header('speaking')}<div class="lesson-grid"><section class="lesson-main"><div class="speaking-card"><p class="eyebrow">PART 1</p><h3>Do you often use public transport?</h3><p>回答结构：直接回答 + 原因 + 一个具体细节。目标 20–30 秒。</p></div><div class="speaking-card"><p class="eyebrow">PART 2</p><h3>Describe a journey you remember well.</h3><p>You should say: where you went; who you travelled with; what happened; and explain why you remember it.</p></div><div class="record-timer" id="speakTimer">01:00</div><button class="complete-lesson" data-speaking-timer>开始 1 分钟准备</button><div class="exercise"><label>录音后写下一个需要修正的问题<input id="speakingNote" type="text" placeholder="例如：停顿太多；反复使用 very"></label></div>${footer('speaking')}</section><aside class="lesson-aside"><h3>口语评分关注</h3><ul class="instruction-list"><li>流利与连贯</li><li>词汇范围与准确性</li><li>语法多样性与准确性</li><li>发音清晰度</li></ul><p class="plan-advice">不要追求口音。目标是清楚、自然、持续表达。</p></aside></div>`; }
function practicalView(){ const {track,scene}=todaysPractical();return `${header('practical')}<div class="lesson-grid"><section class="lesson-main"><div class="scenario-head"><span class="step-chip">${track.title}</span><h3>${track.label} · ${scene}</h3><p>今天的目标不是背句子，而是在这个场景中完成一次真实沟通。</p></div><div class="scenario-steps"><article><span>1</span><div><strong>理解场景</strong><p>写下对方可能会问你的 3 个问题，以及你必须确认的关键信息。</p></div></article><article><span>2</span><div><strong>掌握可迁移表达</strong><ul>${track.phrases.map(p=>`<li><button class="phrase-button" data-say-phrase="${esc(p)}">${esc(p)} <small>点击朗读</small></button></li>`).join('')}</ul></div></article><article><span>3</span><div><strong>完成输出</strong><p>用上面至少两个表达，连续说 60–90 秒；录音后重说一次。</p></div></article></div><div class="exercise"><label>写下今天真正能使用的一段话<textarea id="practicalDraft" rows="6" placeholder="Write what you would actually say in this situation..."></textarea></label><div class="feedback" id="practicalWordCount">0 词 · 目标 50–80 词</div></div>${footer('practical')}</section><aside class="lesson-aside"><h3>三条长期能力线</h3><div class="track-list">${practicalTracks.map(t=>`<div class="track-item ${t.key===track.key?'active':''}"><strong>${t.label}</strong><span>${t.scenes.length} 个核心场景 · ${t.key===track.key?'今日训练':'按天轮换'}</span></div>`).join('')}</div><p class="plan-advice">生活、留学、职场场景每三天轮换一次；接近考试时缩短时长，但不完全中断。</p></aside></div>`; }
function reviewView(){ return `${header('review')}<div class="lesson-grid"><section class="lesson-main"><h3>完成今天的闭环</h3><div class="review-checks">${['我复习了今天的核心词汇','我能解释听力和阅读错题','写作与口语都完成了输出','我完成了今天的真实场景英语','我知道明天只改进哪一件事'].map(x=>`<label><input type="checkbox" data-review-check>${x}</label>`).join('')}</div><div class="exercise"><label>今天最重要的收获<textarea id="dailyWin" rows="3"></textarea></label><label>明天只改进一件事<input id="tomorrowFocus" type="text"></label></div>${footer('review')}</section><aside class="lesson-aside"><h3>完成情况</h3><div class="record-timer" id="dayCompletion">0%</div><p>同时复盘两个问题：这能否提高 IELTS 分数？我能否在海外真实场景中使用？</p></aside></div>`; }
function progressView(){ const scores=[...(state.scores||[])].reverse().slice(0,5); return `${header('progress')}<div class="lesson-grid"><section class="lesson-main"><h3>备考设置</h3><form id="courseSettings" class="review-form"><label>计划开始日期<input id="courseStart" type="date" value="${state.startDate}"></label><label>预计考试日期<input id="courseExam" type="date" value="${state.examDate||''}"></label><label>每日学习时长<select id="courseMinutes"><option value="120" ${state.dailyMinutes===120?'selected':''}>2 小时</option><option value="150" ${state.dailyMinutes===150?'selected':''}>2.5 小时</option><option value="180" ${state.dailyMinutes===180?'selected':''}>3 小时</option></select></label><label>当前最弱项<select id="courseWeak"><option value="">尚未确定</option>${[['listening','听力'],['reading','阅读'],['writing','写作'],['speaking','口语']].map(x=>`<option value="${x[0]}" ${state.weakSkill===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><button class="primary-button" type="submit">保存备考设置</button></form><div class="exercise"><h3>最近模考</h3>${scores.length?scores.map(s=>`<div class="score-row"><time>${s.date}</time><span>听 ${s.l}</span><span>读 ${s.r}</span><span>写 ${s.w}</span><span>说 ${s.s}</span><strong>${s.overall.toFixed(1)}</strong></div>`).join(''):'<p class="empty">尚未记录模考成绩。完成第一次基线测试后，可在原始仪表盘中录入。</p>'}</div><div class="exercise"><h3>四阶段路线</h3><div class="resource-list">${phases.map((p,i)=>`<div class="resource-item"><strong>${i+1}. ${p.title} · 第 ${p.start}–${p.end} 天</strong><span>${p.goal}；${p.target}</span></div>`).join('')}</div></div></section><aside class="lesson-aside"><h3>完整备考资料</h3><div class="resource-list"><div class="resource-item"><strong>真题主线</strong><span>剑桥雅思 12–19，按阶段从单篇到整套</span></div><div class="resource-item"><strong>词汇</strong><span>按主题学习搭配与例句，不孤立背单词</span></div><div class="resource-item"><strong>写作</strong><span>Task 1 图表语言 + Task 2 观点论证</span></div><div class="resource-item"><strong>口语</strong><span>Part 1 短答、Part 2 叙述、Part 3 深入讨论</span></div></div></aside></div>${footer('progress')}`; }

function completedSessions(route){ return Object.values(state.courseCompleted||{}).filter(day=>day&&day[route]).length; }
function courseIntroView(route){ const m=courseMeta[route],sessions=completedSessions(route),doneToday=isDone(route),vocab=route==='vocabulary',mastered=(state.masteredWords||[]).length,total=allWords().length; const percent=vocab?Math.round(mastered/Math.max(total,1)*100):Math.min(100,Math.round(sessions/180*100)); const brief=route==='vocabulary'?['20 个学术核心词','英文定义、同义词和语境例句','比较与对比语法仿写']:route==='listening'?['盲听抓取场景','数字、日期与拼写','对照文本精听跟读']:route==='reading'?['一篇学术短文','判断题与原文定位','同义替换复盘']:route==='writing'?['Task 2 审题','主体段四步结构','80–110 词限时输出']:route==='speaking'?['Part 1 短答','Part 2 话题卡','计时录音与复盘']:route==='practical'?[`${todaysPractical().track.label}：${todaysPractical().scene}`,'3 个可迁移表达','一次 60–90 秒真实输出']:['核对今日全部学习','同时复盘分数与应用能力','确定明日唯一改进点']; return `${header(route)}<div class="course-entry"><section class="entry-progress"><div class="entry-progress-head"><div><p class="eyebrow">MY PROGRESS</p><h3>我的${m[0]}学习进度</h3></div><strong>${vocab?`${mastered} / ${total}`:`${sessions} 次`}</strong></div><div class="entry-progress-bar"><span style="width:${percent}%"></span></div><div class="entry-stats"><div><span>今天</span><strong>${doneToday?'已完成':'待学习'}</strong></div><div><span>${vocab?'当前词库':'累计训练'}</span><strong>${vocab?`${total} 词`:`${sessions} 天`}</strong></div><div><span>今日安排</span><strong>${m[2]}</strong></div></div>${vocab?`<div class="vocab-level-note"><strong>词汇目标说明</strong><p>当前 1,000 词是第一层学术核心词，不是 IELTS 的全部词汇。建议逐步建立约 4,000–6,000 个识别词汇，并重点掌握主题搭配、同义替换和准确使用。</p></div>`:''}</section><section class="today-brief"><span class="step-chip">第 1 步 / 共 2 步</span><h3>今天将学习什么</h3><ul class="instruction-list">${brief.map(x=>`<li>${x}</li>`).join('')}</ul><button class="start-learning-button" data-start-course="${route}">开始进入学习</button></section></div>`; }
const views={overview:overviewView,vocabulary:()=>courseIntroView('vocabulary'),'vocabulary-study':vocabularyView,listening:()=>courseIntroView('listening'),'listening-study':listeningView,reading:()=>courseIntroView('reading'),'reading-study':readingView,writing:()=>courseIntroView('writing'),'writing-study':writingView,speaking:()=>courseIntroView('speaking'),'speaking-study':speakingView,practical:()=>courseIntroView('practical'),'practical-study':practicalView,review:()=>courseIntroView('review'),'review-study':reviewView,progress:progressView};
function navigate(route,push=true){ if(!views[route]) route='overview'; document.getElementById('lessonApp').innerHTML=views[route](); const base=route.replace('-study',''); document.querySelectorAll('.course-nav .nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===base)); if(push) history.replaceState(null,'',`#course-${route}`); bindView(route); document.getElementById('lessonApp').focus({preventScroll:true}); window.scrollTo({top:0,behavior:'smooth'}); }
function updateCourseNav(){ document.querySelectorAll('.course-nav [data-route]').forEach(b=>{ const done=isDone(b.dataset.route); b.classList.toggle('completed',done); const small=b.querySelector('small'); if(done&&small) small.textContent='已完成'; }); }
function speak(text,rate=.85){ if(!('speechSynthesis' in window)){showToast('当前浏览器不支持语音朗读。');return;} speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='en-GB';u.rate=rate;speechSynthesis.speak(u); }
function attachWordListeners(){
  document.querySelectorAll('[data-word]').forEach(b=>b.addEventListener('click',()=>{const w=activeWords[Number(b.dataset.word)], box=document.getElementById('wordDetail');document.querySelectorAll('[data-word]').forEach(x=>x.setAttribute('aria-expanded','false'));b.setAttribute('aria-expanded','true');box.classList.remove('view-hidden');const mastered=(state.masteredWords||[]).includes(w.word);box.innerHTML=`<h3>${esc(w.word)} ${w.phonetic?`<span class="phonetic">${esc(w.phonetic)}</span>`:''}</h3><p><strong>${esc(w.pos||'word')}</strong> · 难度 ${esc(w.difficulty||3)}/5 · ${esc(w.theme||'Academic')}</p><p class="meaning">${esc(w.meaning)}</p>${w.synonyms?.length?`<p><strong>同义词：</strong>${w.synonyms.map(esc).join(', ')}</p>`:''}<p class="example">${esc(w.example_sentence||'')}${w.example_zh?`<br>${esc(w.example_zh)}`:''}</p><div class="word-actions"><button class="mini-button" data-say-word>朗读单词</button><button class="mini-button" data-say-example>朗读例句</button><button class="mini-button" data-master-word>${mastered?'取消已掌握':'标记已掌握'}</button></div>`;box.querySelector('[data-say-word]').onclick=()=>speak(w.word,.75);box.querySelector('[data-say-example]').onclick=()=>speak(w.example_sentence,.82);box.querySelector('[data-master-word]').onclick=()=>{const set=new Set(state.masteredWords||[]);set.has(w.word)?set.delete(w.word):set.add(w.word);state.masteredWords=[...set];saveState();navigate('vocabulary-study',false);showToast(set.has(w.word)?'已加入掌握词汇。':'已移回待学习词汇。');};box.scrollIntoView({behavior:'smooth',block:'nearest'});}));
}
function renderWordResults(useDaily=false){ const grid=document.getElementById('wordGrid'); if(!grid)return; if(useDaily){activeWords=dailyWords();document.getElementById('wordSearch').value='';document.getElementById('wordTheme').value='';document.getElementById('wordDifficulty').value='';}else{const q=document.getElementById('wordSearch').value.trim().toLowerCase(),theme=document.getElementById('wordTheme').value,difficulty=document.getElementById('wordDifficulty').value;activeWords=allWords().filter(w=>(!q||`${w.word} ${w.meaning} ${w.theme} ${(w.synonyms||[]).join(' ')}`.toLowerCase().includes(q))&&(!theme||w.theme===theme)&&(!difficulty||String(w.difficulty)===difficulty)).slice(0,100);} grid.innerHTML=activeWords.map(wordCard).join('')||'<p class="empty">没有匹配结果，请调整搜索条件。</p>';document.getElementById('wordResultCount').textContent=useDaily?'显示今日 20 词':`找到 ${activeWords.length}${activeWords.length===100?'（最多显示前 100 条）':''}`;document.getElementById('wordDetail').classList.add('view-hidden');attachWordListeners(); }
function changeWordBank(bank){ selectedWordBank=bank;const theme=document.getElementById('wordTheme'),difficulty=document.getElementById('wordDifficulty'),search=document.getElementById('wordSearch');if(!theme)return;theme.innerHTML='<option value="">全部主题</option>'+[...new Set(allWords().map(w=>w.theme).filter(Boolean))].sort().map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');difficulty.value='';search.value='';renderWordResults(false); }
function renderDailyCefrWords(){ selectedWordBank='cefr';const select=document.getElementById('wordBankSelect');if(select)select.value='cefr';changeWordBank('cefr');activeWords=dailyCefrWords();document.getElementById('wordGrid').innerHTML=activeWords.map(wordCard).join('')||'<p class="empty">CEFR词库仍在加载，请稍后重试。</p>';document.getElementById('wordResultCount').textContent=`显示今日 ${activeWords.length} 个 CEFR 识别词 · 约 177 天覆盖 8,827 词`;attachWordListeners(); }
function bindView(route){
  document.querySelectorAll('[data-start-course]').forEach(b=>b.addEventListener('click',()=>navigate(`${b.dataset.startCourse}-study`)));
  document.querySelectorAll('[data-route-link]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.routeLink)));
  document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>{markDone(b.dataset.complete);navigate(b.dataset.next)}));
  attachWordListeners();
  document.getElementById('wordSearch')?.addEventListener('input',()=>renderWordResults(false));
  document.getElementById('wordBankSelect')?.addEventListener('change',e=>changeWordBank(e.target.value));
  document.getElementById('wordTheme')?.addEventListener('change',()=>renderWordResults(false));
  document.getElementById('wordDifficulty')?.addEventListener('change',()=>renderWordResults(false));
  document.getElementById('showDailyWords')?.addEventListener('click',()=>{selectedWordBank='academic';const select=document.getElementById('wordBankSelect');if(select)select.value='academic';changeWordBank('academic');renderWordResults(true);});
  if(document.getElementById('showDailyWords')&&!document.getElementById('showDailyCefr'))document.getElementById('showDailyWords').insertAdjacentHTML('afterend','<button class="mini-button" id="showDailyCefr">今日 CEFR 50 词</button>');
  document.getElementById('showDailyCefr')?.addEventListener('click',renderDailyCefrWords);
  document.querySelector('[data-check-grammar]')?.addEventListener('click',()=>{const v=document.getElementById('grammarAnswer').value.trim();document.getElementById('grammarFeedback').textContent=v.length>18&&/whereas|while/i.test(v)?'结构正确。再检查主谓和时态。':'请写一个完整句，并使用 whereas 或 while。';});
  document.querySelector('[data-speak-listening]')?.addEventListener('click',()=>speak("Good morning, Westfield Community Centre. Hello, I'd like to enrol in the beginner photography course. Certainly. It starts on the fifteenth of September and runs for six weeks. Classes are held on Thursday evenings from six thirty to eight. The total fee is ninety-five pounds, including materials.",.78));
  document.querySelector('[data-check-listening]')?.addEventListener('click',()=>{let n=0;document.querySelectorAll('[data-listening-answer]').forEach(x=>{if(x.value.toLowerCase().includes(x.dataset.listeningAnswer.toLowerCase()))n++});document.getElementById('listeningFeedback').textContent=`答对 ${n}/3。错误项请回到文本定位原句并跟读。`;});
  document.querySelector('[data-check-reading]')?.addEventListener('click',()=>{let n=0;document.querySelectorAll('.question').forEach(q=>{const x=q.querySelector('input:checked');if(x&&x.value===x.dataset.correct)n++});document.getElementById('readingFeedback').textContent=`答对 ${n}/3。证据依次在第 1 段末、第 2 段末；第 3 题原文没有说明“所有商家”。`;});
  document.getElementById('writingDraft')?.addEventListener('input',e=>{const n=e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0;document.getElementById('wordCount').textContent=`${n} 词 · 目标 80–110 词`;state.drafts=state.drafts||{};state.drafts.writing=e.target.value;saveState();});
  if(document.getElementById('writingDraft')&&state.drafts?.writing){document.getElementById('writingDraft').value=state.drafts.writing;document.getElementById('writingDraft').dispatchEvent(new Event('input'));}
  document.querySelector('[data-speaking-timer]')?.addEventListener('click',e=>{let left=60;e.target.disabled=true;const el=document.getElementById('speakTimer'),iv=setInterval(()=>{left--;el.textContent=`00:${String(left).padStart(2,'0')}`;if(left<=0){clearInterval(iv);e.target.disabled=false;e.target.textContent='开始 2 分钟作答';el.textContent='02:00';showToast('准备结束，现在开始作答并录音。');}},1000);});
  document.querySelectorAll('[data-say-phrase]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.sayPhrase,.82)));
  document.getElementById('practicalDraft')?.addEventListener('input',e=>{const n=e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0;document.getElementById('practicalWordCount').textContent=`${n} 词 · 目标 50–80 词`;state.drafts=state.drafts||{};state.drafts.practical=e.target.value;saveState();});
  if(document.getElementById('practicalDraft')&&state.drafts?.practical){document.getElementById('practicalDraft').value=state.drafts.practical;document.getElementById('practicalDraft').dispatchEvent(new Event('input'));}
  document.querySelectorAll('[data-review-check]').forEach(x=>x.addEventListener('change',()=>{const all=[...document.querySelectorAll('[data-review-check]')],n=all.filter(x=>x.checked).length;document.getElementById('dayCompletion').textContent=`${Math.round(n/all.length*100)}%`;}));
  document.getElementById('courseSettings')?.addEventListener('submit',e=>{e.preventDefault();state.startDate=document.getElementById('courseStart').value;state.examDate=document.getElementById('courseExam').value;state.dailyMinutes=Number(document.getElementById('courseMinutes').value);state.weakSkill=document.getElementById('courseWeak').value;saveState();showToast('备考设置已保存。');render();});
  updateCourseNav();
}

document.querySelectorAll('.course-nav [data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));
const initial=location.hash.startsWith('#course-')?location.hash.replace('#course-',''):'overview';
navigate(initial,false);
Promise.all([fetch('./data/ielts-core-1000.json').then(r=>{if(!r.ok)throw new Error(`Academic words HTTP ${r.status}`);return r.json();}),fetch('./data/cefr-word-list.csv').then(r=>{if(!r.ok)throw new Error(`CEFR words HTTP ${r.status}`);return r.text();}),fetch('./data/cefr-c1-c2-word-list.csv').then(r=>{if(!r.ok)throw new Error(`Advanced CEFR words HTTP ${r.status}`);return r.text();})]).then(([words,cefr,advanced])=>{wordBank=words;cefrBank=mergeCefrWords(parseCefrCsv(cefr),parseAdvancedCefrCsv(advanced));if(location.hash==='#course-vocabulary'||location.hash==='#course-vocabulary-study')navigate(location.hash.endsWith('-study')?'vocabulary-study':'vocabulary',false);}).catch(()=>showToast('词库加载失败，已切换到内置核心词。'));
