(() => {
  'use strict';
  const STORE_KEY = 'ielts-sentence-lab-mvp-v1.1.1';
  const DICTATION_KEY = 'ielts-sentence-lab-current-dictation-v1.3';
  const LONGMAN_BASE_URL = 'https://www.ldoceonline.com/dictionary/';
  const readingSentences = [
    ['Urban green spaces play an important role in the health of modern cities.','城市绿地对现代城市的健康发挥着重要作用。'],
    ['They provide residents with places to exercise, relax and meet other people.','它们为居民提供锻炼、放松和与他人见面的场所。'],
    ['Researchers have also linked access to parks with lower levels of stress.','研究人员还发现，接触公园与较低的压力水平有关。'],
    ['However, these benefits are not distributed equally across the population.','然而，这些益处并未在人群中得到公平分配。'],
    ['Wealthier neighbourhoods often contain more trees and better maintained parks.','较富裕的社区通常拥有更多树木和维护更好的公园。'],
    ['In contrast, densely populated districts may have very little public space.','相比之下，人口密集的地区可能几乎没有公共空间。'],
    ['This difference can influence both physical and mental health.','这种差异会影响身体和心理健康。'],
    ['Some city governments are therefore changing the way they plan new developments.','因此，一些城市政府正在改变规划新开发项目的方式。'],
    ['Instead of building one large park, they create smaller green areas throughout a district.','他们不再只建一个大型公园，而是在整个地区建设较小的绿地。'],
    ['The approach makes nature accessible to people who cannot travel far.','这种方法让无法远行的人也能接触自然。'],
    ['It can also reduce summer temperatures by providing shade near homes.','它还可以通过在住宅附近提供阴凉来降低夏季温度。'],
    ['Nevertheless, creating a park is only the first step.','尽管如此，建设公园只是第一步。'],
    ['Local authorities must provide funding for long-term maintenance.','地方政府必须为长期维护提供资金。'],
    ['Residents should also be involved in decisions about how the space is used.','居民也应参与决定空间的使用方式。'],
    ['When communities feel ownership, public spaces are more likely to remain welcoming and safe.','当社区产生归属感时，公共空间更有可能保持友好和安全。']
  ];
  const listeningSentences = [
    ['Good morning, everyone, and welcome to the Riverside Visitor Centre.','大家早上好，欢迎来到河畔游客中心。',0,5200],
    ['Before the tour begins, I would like to explain today’s schedule.','在游览开始之前，我想说明一下今天的安排。',5400,11100],
    ['We will leave the main building at half past nine.','我们将在九点半离开主楼。',11300,15800],
    ['Our first stop will be the old railway bridge beside the river.','第一站是河边的老铁路桥。',16000,21700],
    ['Please stay on the marked path because the ground is wet.','请沿着有标记的小路行走，因为地面很湿。',21900,27500],
    ['The walk to the bridge takes approximately twenty minutes.','步行到桥边大约需要二十分钟。',27700,33000],
    ['After that, you will have some free time in the garden.','之后，大家可以在花园里自由活动。',33200,38600],
    ['Lunch is available in the café from twelve o’clock.','咖啡馆从十二点开始供应午餐。',38800,43800],
    ['Vegetarian meals can be ordered at the front desk.','素食餐可以在前台预订。',44000,49000],
    ['The return bus will depart from the entrance at three fifteen.','返程巴士将在三点十五分从入口处出发。',49200,55000],
    ['If you have any questions, please speak to a member of staff.','如果有任何问题，请咨询工作人员。',55200,60800],
    ['Now, let us begin with a short safety announcement.','现在，让我们先听一段简短的安全说明。',61000,66200]
  ];
  const makeSentences = (materialId, rows, kind) => rows.map((row,i)=>({id:`${materialId}-s${i+1}`,materialId,orderIndex:i,textEn:row[0],textZh:row[1],audioKind:kind,audioPath:kind==='original'?`data/listening-sentences/${String(i+1).padStart(2,'0')}.wav`:null}));
  const seed = {
    version:'1.1', settings:{playbackRate:1,repeatCount:1,pauseSeconds:1.5,autoContinue:false,showEnglish:false,showChinese:false,highlightVocabulary:true},
    materials:[
      {id:'listen-riverside',collection:'MVP Test Library',title:'Riverside Visitor Centre',testNo:1,skill:'listening',sectionNo:1,audioKind:'original',audioPath:'data/riverside-listening.wav',description:'Listening Part 1 · 测试原始音频'},
      {id:'read-green-cities',collection:'MVP Test Library',title:'Green Spaces in Modern Cities',testNo:1,skill:'reading',sectionNo:1,audioKind:'generated_reading_audio',description:'Academic Reading Passage 1 · Generated Audio'}
    ],
    sentences:[...makeSentences('listen-riverside',listeningSentences,'original'),...makeSentences('read-green-cities',readingSentences,'generated_reading_audio')],
    progress:{'listen-riverside':{currentSentenceIndex:0,completedSentenceCount:0},'read-green-cities':{currentSentenceIndex:0,completedSentenceCount:0}}, vocabulary:[],occurrences:[],currentMaterialId:'listen-riverside'
  };
  const episodeRange=(start,end)=>Array.from({length:end-start+1},(_,i)=>start+i);
  const localSeries=[
    ['奇妙岛屿',episodeRange(1,26)],['无尽汪洋',episodeRange(1,24)],['海洋岛屿',episodeRange(1,35)],['漂流者',episodeRange(1,31)],['火山列岛',episodeRange(1,21)],['脆弱天堂',[...episodeRange(1,15),...episodeRange(18,23)]]
  ];
  const libraryCollections=[{id:'local-lrc',title:'英语听力逐句资料',localLrc:true},{id:'official-samples',title:'Official IELTS Samples',official:true},...[21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4].map(book=>({id:`cambridge-${book}`,title:`Cambridge IELTS ${book} Academic`,book}))];
  let state = load(); state.sentences.filter(s=>s.materialId==='listen-riverside').forEach((s,i)=>{s.audioPath=`data/listening-sentences/${String(i+1).padStart(2,'0')}.wav`;delete s.startMs;delete s.endMs});state.materials.filter(m=>m.skill==='reading').forEach(m=>m.audioKind='generated_reading_audio');state.sentences.filter(s=>s.materialId==='read-green-cities').forEach(s=>s.audioKind='generated_reading_audio'); let audio = new Audio(); let playing=false, frame=0, repeatRemaining=0, activeSelection=null, editVocabId=null, pauseTimer=0, dictation=loadDictation(),currentCollectionId='cambridge-21';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function load(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));return saved?.version==='1.1'?saved:structuredClone(seed)}catch{return structuredClone(seed)}}
  function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state)); updateCount()}
  function blankDictation(sentenceId){return {sentenceId,draftText:'',firstAttemptText:'',submitted:false,skipped:false,comparing:false}}
  function loadDictation(){try{return JSON.parse(localStorage.getItem(DICTATION_KEY))||blankDictation('')}catch{return blankDictation('')}}
  function ensureDictation(){const id=currentSentence().id;if(dictation.sentenceId!==id){dictation=blankDictation(id);saveDictation()}return dictation}
  function saveDictation(){localStorage.setItem(DICTATION_KEY,JSON.stringify(dictation))}
  function resetDictation(){dictation=blankDictation(currentSentence().id);saveDictation()}
  function updateCount(){const el=$('#vocabCount');if(el)el.textContent=state.vocabulary.length}
  function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
  function source(material){return material.description||`${material.collection} · Test ${material.testNo} · ${material.skill==='listening'?'Listening Part':'Reading Passage'} ${material.sectionNo}`}
  function currentMaterial(){return state.materials.find(m=>m.id===state.currentMaterialId)||state.materials[0]}
  function currentSentences(){return state.sentences.filter(s=>s.materialId===currentMaterial().id).sort((a,b)=>a.orderIndex-b.orderIndex)}
  function currentSentence(){return currentSentences()[state.progress[currentMaterial().id]?.currentSentenceIndex||0]}
  function route(){stopAudio();const name=(location.hash.slice(1).split('?')[0]||'library');render(name)}
  function setHead(eyebrow,title){$('#pageEyebrow').textContent=eyebrow;$('#pageTitle').textContent=title;$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===location.hash.slice(1).split('?')[0]||(!location.hash&&a.dataset.route==='library')))}
  function render(name){if(name==='material')return renderMaterial();if(name==='study')return renderStudy();if(name==='vocabulary')return renderVocabulary();if(name==='collection')return renderCollection();return renderLibraryV12()}
  function renderLibrary(){setHead('YOUR LIBRARY','资料库');const cards=state.materials.map(m=>{const p=state.progress[m.id],count=state.sentences.filter(s=>s.materialId===m.id).length,pc=Math.round((p.completedSentenceCount/count)*100);return `<article class="card"><p class="eyebrow">${m.skill==='listening'?'LISTENING · ORIGINAL AUDIO':'ACADEMIC READING · TTS'}</p><h3>${esc(m.title)}</h3><p>${esc(source(m))}</p><progress max="${count}" value="${p.completedSentenceCount}"></progress><div class="card-footer"><span class="meta">${p.completedSentenceCount} / ${count} 句 · ${pc}%</span><button class="secondary-btn open-material" data-id="${m.id}">查看材料</button></div></article>`}).join('');$('#app').innerHTML=`<section class="app-page"><div class="hero-card"><div><p class="eyebrow">SENTENCE BY SENTENCE</p><h2>听一句，理解一句，再进入下一句。</h2><p>唯一学习流程：盲听 → 显示英文 → 查词 → 按需显示中文 → 重听。</p></div><div class="progress-ring"><strong>${state.materials.length}</strong><span>个测试材料</span></div></div><div class="section-head"><div><p class="eyebrow">MVP TEST LIBRARY</p><h2>Materials</h2></div><span class="meta">1 Listening · 1 Reading</span></div><div class="card-grid">${cards}</div></section>`;$$('.open-material').forEach(b=>b.onclick=()=>{state.currentMaterialId=b.dataset.id;save();location.hash='material'})}
  function renderLibraryV12(){
    setHead('YOUR LIBRARY','资料库');
    const demoCards=state.materials.filter(m=>['listen-riverside','read-green-cities'].includes(m.id)).map(m=>{const p=state.progress[m.id],count=state.sentences.filter(s=>s.materialId===m.id).length,pc=Math.round((p.completedSentenceCount/count)*100),label=m.skill==='listening'?'DEMO LISTENING · TEST AUDIO':'READING → LISTENING · GENERATED AUDIO';return `<article class="card"><p class="eyebrow">${label}</p><h3>${esc(m.title)}</h3><p>${esc(source(m))}</p><progress max="${count}" value="${p.completedSentenceCount}"></progress><div class="card-footer"><span class="meta">${p.completedSentenceCount} / ${count} 句 · ${pc}%</span><button class="secondary-btn open-material" data-id="${m.id}">查看材料</button></div></article>`}).join('');
    const collectionCards=libraryCollections.map(c=>{const audioReady=c.book>=4&&c.book<=20;if(c.localLrc)return `<article class="card library-collection"><p class="eyebrow">LOCAL AUDIO + LRC</p><h3>${esc(c.title)}</h3><p>6 个系列 · 158 组音频与英文字幕</p><div class="waiting-state"><span class="status-dot ready"></span>可按完整英文句子逐句学习</div><div class="card-footer"><span class="meta">来自 data/IELTS 根目录</span><button class="secondary-btn open-collection" data-id="${c.id}">查看材料</button></div></article>`;return `<article class="card library-collection"><p class="eyebrow">${c.official?'OFFICIAL FREE SOURCE':'CAMBRIDGE ACADEMIC'}</p><h3>${esc(c.title)}</h3><p>${c.official?'等待导入官方免费材料':'4 Tests · 16 Listening Parts · 4 Full Tests'}</p><div class="waiting-state"><span class="status-dot ${audioReady?'ready':'waiting'}"></span>${c.official?'Waiting for source files':audioReady?'20 个原始音频已编入资料库 · 等待 transcript':'20 materials · Waiting for source files'}</div><div class="card-footer"><span class="meta">${audioReady?'来自 data/IELTS/电台节目':'不含受版权保护内容'}</span><button class="secondary-btn open-collection" data-id="${c.id}">查看结构</button></div></article>`}).join('');
    $('#app').innerHTML=`<section class="app-page"><div class="hero-card"><div><p class="eyebrow">SENTENCE BY SENTENCE · v1.3</p><h2>原声 → 第一遍听写 → 英文对照 → 生词</h2><p>已递归编入 data/IELTS 的 498 个 MP3；有 LRC 的材料可逐句学习，其余等待 transcript。</p></div><div class="progress-ring"><strong>498</strong><span>个本地 MP3</span></div></div><div class="section-head"><div><p class="eyebrow">READY TO USE</p><h2>功能测试材料</h2></div><span class="meta">仅用于体验当前学习流程</span></div><div class="card-grid">${demoCards}</div><div class="section-head"><div><p class="eyebrow">LOCAL IELTS LIBRARY</p><h2>本地资料库</h2></div><span class="meta">158 组带 LRC · 电台节目 340 个 MP3</span></div><div class="card-grid library-grid">${collectionCards}</div></section>`;
    $$('.open-material').forEach(b=>b.onclick=()=>{state.currentMaterialId=b.dataset.id;save();location.hash='material'});$$('.open-collection').forEach(b=>b.onclick=()=>{currentCollectionId=b.dataset.id;location.hash='collection'});
  }
  function renderCollection(){
    const collection=libraryCollections.find(c=>c.id===currentCollectionId)||libraryCollections[1];setHead('LIBRARY COLLECTION',collection.title);
    if(collection.localLrc){renderLocalLrcCollection();return}
    if(collection.official){$('#app').innerHTML=`<section class="app-page"><button class="secondary-btn back-library">← 返回资料库</button><div class="panel empty-state"><p class="eyebrow">OFFICIAL IELTS SAMPLES</p><h2>Waiting for source files</h2><p>导入官方免费 Academic sample materials 后，内容将使用同一个逐句听写页面。</p></div></section>`;$('.back-library').onclick=()=>location.hash='library';return}
    const audioCount=collection.book>=4&&collection.book<=20?20:0;const tests=[1,2,3,4].map(test=>{const listening=[1,2,3,4].map(part=>radioUnit(collection.book,test,part)).join(''),full=radioUnit(collection.book,test,null);return `<details class="test-group" ${test===1?'open':''}><summary><strong>Test ${test}</strong><span>${audioCount?'5 audio files':'5 materials · Waiting'}</span></summary><div class="unit-section"><h3>Listening Parts</h3>${listening}</div><div class="unit-section"><h3>Full Test Audio</h3>${full}</div></details>`}).join('');
    $('#app').innerHTML=`<section class="app-page"><button class="secondary-btn back-library">← 返回资料库</button><div class="collection-summary"><div><p class="eyebrow">CAMBRIDGE IELTS ${collection.book} ACADEMIC</p><h2>4 Tests · 20 audio files</h2><p>${audioCount?`${audioCount} 个原始音频已关联。完成离线英文转写后可进入逐句学习，转写内容需要人工校对。`:'等待用户合法提供原始音频。'}</p></div><span class="waiting-pill">${audioCount?'Transcribing locally':'Waiting for source files'}</span></div><div class="test-list">${tests}</div></section>`;$('.back-library').onclick=()=>location.hash='library';$$('.open-radio-transcript').forEach(button=>button.onclick=()=>loadRadioTranscript(Number(button.dataset.book),Number(button.dataset.test),button.dataset.part?Number(button.dataset.part):null,button));
  }
  function radioName(book,test,suffix=''){if(book<4||book>20)return '';const shownTest=book===12?test+4:test,sectionWord=book<=14?'Section':'Part',prefix=book===19?'【新】':book===20?'【最新】':'',testWord=book===20?'Text':'Test',correction=book===7&&test===3&&suffix===3?' 更正版':'';return `data/IELTS/电台节目/之昂张张张zzz - ${prefix}IELTS${book} ${testWord}${shownTest}${suffix?` ${sectionWord}${suffix}${correction}`:''}.mp3`}
  function localAudioPath(book,test,part){return radioName(book,test,part)}
  function localFullTestAudioPath(book,test){return radioName(book,test)}
  function radioUnit(book,test,part){const audioPath=part?localAudioPath(book,test,part):localFullTestAudioPath(book,test),label=part?`Part ${part}`:`完整 Test ${test}`;return `<div class="material-row audio-ready"><div><strong>${label}</strong><span>Listening</span></div><p>原始音频已就绪 · AI英文转写</p><button class="secondary-btn open-radio-transcript" data-book="${book}" data-test="${test}" ${part?`data-part="${part}"`:''}>载入英文原文</button></div>`}
  function waitingUnit(type,unit,policy,audioPath=''){return `<div class="material-row ${audioPath?'audio-ready':''}"><div><strong>${unit}</strong><span>${type}</span></div><p>${audioPath?'原始音频已就绪 · 等待 transcript':policy}</p><button disabled>${audioPath?'等待 transcript':'等待源文件'}</button></div>`}
  function renderLocalLrcCollection(){const groups=localSeries.map(([name,episodes])=>`<details class="test-group"><summary><strong>${esc(name)}</strong><span>${episodes.length} 组 · Audio + LRC</span></summary><div class="unit-section local-episode-grid">${episodes.map(index=>`<button class="secondary-btn open-local-episode" data-series="${esc(name)}" data-index="${index}">${String(index).padStart(2,'0')} · 逐句学习</button>`).join('')}</div></details>`).join('');$('#app').innerHTML=`<section class="app-page"><button class="secondary-btn back-library">← 返回资料库</button><div class="collection-summary"><div><p class="eyebrow">LOCAL AUDIO + LRC</p><h2>158 组可逐句学习材料</h2><p>LRC 时间轴会按英文句末标点合并，播放时从完整句首到下一句开始。</p></div><span class="waiting-pill">Ready for sentence learning</span></div><div class="test-list">${groups}</div></section>`;$('.back-library').onclick=()=>location.hash='library';$$('.open-local-episode').forEach(b=>b.onclick=()=>loadLocalEpisode(b.dataset.series,Number(b.dataset.index)))}
  async function loadLocalEpisode(series,index){const displayNumber=String(index).padStart(2,'0'),fileNumber=series==='海洋岛屿'?String(index):displayNumber,base=`data/IELTS/英语听力 - ${series} ${fileNumber}`,button=document.activeElement;button.disabled=true;button.textContent='载入中…';try{const response=await fetch(`${base}.lrc`);if(!response.ok)throw new Error('LRC unavailable');const rows=parseLrc(await response.text()),id=`local-${series}-${displayNumber}`,material={id,collection:'英语听力逐句资料',title:`${series} ${displayNumber}`,testNo:index,skill:'listening',sectionNo:1,audioKind:'original',audioPath:`${base}.mp3`,description:`${series} · 第 ${displayNumber} 集`};state.materials=state.materials.filter(m=>m.id!==id);state.sentences=state.sentences.filter(s=>s.materialId!==id);state.materials.push(material);state.sentences.push(...rows.map((row,i)=>({id:`${id}-s${i+1}`,materialId:id,orderIndex:i,textEn:row.text,textZh:'',audioKind:'original',audioPath:material.audioPath,startMs:row.startMs,endMs:row.endMs})));state.progress[id]=state.progress[id]||{currentSentenceIndex:0,completedSentenceCount:0};state.currentMaterialId=id;save();location.hash='material'}catch{button.disabled=false;button.textContent=`${displayNumber} · 逐句学习`;toast('无法读取这组 LRC 文件')}}
  function parseLrc(text){const lines=text.split(/\r?\n/).map(line=>{const match=line.match(/^\[(\d+):(\d+(?:\.\d+)?)\](.*)$/);return match?{time:(Number(match[1])*60+Number(match[2]))*1000,text:match[3].trim()}:null}).filter(row=>row&&row.text);const sentences=[],buffer=[];for(const line of lines){buffer.push(line);if(/[.!?][”’"']?$/.test(line.text))flush()}flush();function flush(){if(!buffer.length)return;sentences.push({startMs:buffer[0].time,endMs:null,text:buffer.map(x=>x.text).join(' ').replace(/\s+([,.;!?])/g,'$1')});buffer.length=0}return sentences.map((sentence,i)=>({...sentence,endMs:sentences[i+1]?.startMs||null}))}
  function transcriptPath(audioPath){const stem=audioPath.split('/').pop().replace(/\.mp3$/i,'');return `data/IELTS/transcripts/${stem}.json`}
  async function loadRadioTranscript(book,test,part,button){const audioPath=part?localAudioPath(book,test,part):localFullTestAudioPath(book,test);button.disabled=true;button.textContent='载入中…';try{const response=await fetch(transcriptPath(audioPath),{cache:'no-store'});if(!response.ok)throw new Error('not ready');const payload=await response.json(),segments=(payload.transcription||[]).map(item=>({startMs:item.offsets?.from,endMs:item.offsets?.to,text:(item.text||'').trim()})).filter(item=>item.text);if(!segments.length)throw new Error('empty');const rows=mergeTranscriptSegments(segments),suffix=part?`part-${part}`:'full',id=`radio-${book}-${test}-${suffix}`,material={id,collection:`Cambridge IELTS ${book} Academic`,title:`Test ${test} · ${part?`Part ${part}`:'完整 Test'}`,testNo:test,skill:'listening',sectionNo:part||0,audioKind:'original',audioPath,description:`Cambridge IELTS ${book} · Test ${test} · ${part?`Part ${part}`:'完整 Test'} · AI转写待校对`};state.materials=state.materials.filter(m=>m.id!==id);state.sentences=state.sentences.filter(s=>s.materialId!==id);state.materials.push(material);state.sentences.push(...rows.map((row,i)=>({id:`${id}-s${i+1}`,materialId:id,orderIndex:i,textEn:row.text,textZh:'',audioKind:'original',audioPath,startMs:row.startMs,endMs:row.endMs})));state.progress[id]=state.progress[id]||{currentSentenceIndex:0,completedSentenceCount:0};state.currentMaterialId=id;save();location.hash='material'}catch{button.disabled=false;button.textContent='转写尚未完成';toast('这段音频仍在本地转写，请稍后再试')}}
  function mergeTranscriptSegments(segments){const sentences=[],buffer=[];for(const segment of segments){buffer.push(segment);if(/[.!?][”’"']?$/.test(segment.text))flush()}flush();function flush(){if(!buffer.length)return;sentences.push({startMs:buffer[0].startMs,endMs:buffer[buffer.length-1].endMs,text:buffer.map(x=>x.text).join(' ').replace(/\s+([,.;!?])/g,'$1')});buffer.length=0}return sentences}
  function renderMaterial(){const m=currentMaterial(),ss=currentSentences(),p=state.progress[m.id];setHead(m.skill.toUpperCase(),m.title);$('#app').innerHTML=`<section class="app-page"><button class="secondary-btn" id="backLibrary">← 返回资料库</button><div class="panel import-card" style="margin-top:18px"><p class="eyebrow">${m.skill==='listening'?'ORIGINAL AUDIO + TIMESTAMPS':'SENTENCE TTS'}</p><h2>${esc(m.title)}</h2><p>${esc(source(m))}</p><div class="section-head"><span>${ss.length} 个 Sentence</span><span>${p.completedSentenceCount} 已访问</span></div><progress max="${ss.length}" value="${p.completedSentenceCount}"></progress><div class="card-footer"><span class="meta">上次位置：第 ${p.currentSentenceIndex+1} 句</span><button class="primary-btn" id="startMaterial">${p.completedSentenceCount?'继续学习':'开始学习'}</button></div></div></section>`;$('#backLibrary').onclick=()=>location.hash='library';$('#startMaterial').onclick=()=>location.hash='study'}
  function normalizedTokens(text){return text.toLowerCase().replace(/[\u2018\u2019]/g,"'").replace(/[^a-z0-9']+/g,' ').trim().split(/\s+/).filter(Boolean)}
  function compareDictation(actualText,expectedText){
    const actual=normalizedTokens(actualText),expected=normalizedTokens(expectedText),dp=Array.from({length:expected.length+1},()=>Array(actual.length+1).fill(0));
    for(let i=expected.length-1;i>=0;i--)for(let j=actual.length-1;j>=0;j--)dp[i][j]=expected[i]===actual[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);
    const raw=[];let i=0,j=0;
    while(i<expected.length||j<actual.length){if(i<expected.length&&j<actual.length&&expected[i]===actual[j]){raw.push({type:'correct',expected:expected[i++],actual:actual[j++]})}else if(i<expected.length&&(j>=actual.length||dp[i+1][j]>=dp[i][j+1])){raw.push({type:'missing',expected:expected[i++]})}else{raw.push({type:'extra',actual:actual[j++]})}}
    const result=[];for(let k=0;k<raw.length;k++){const here=raw[k],next=raw[k+1];if(next&&here.type==='missing'&&next.type==='extra'){result.push({type:'different',expected:here.expected,actual:next.actual});k++}else if(next&&here.type==='extra'&&next.type==='missing'){result.push({type:'different',expected:next.expected,actual:here.actual});k++}else result.push(here)}return result;
  }
  function renderDiff(textEn){const parts=compareDictation(dictation.firstAttemptText,textEn);const mine=parts.filter(p=>p.type!=='missing').map(p=>`<span class="diff-${p.type}">${esc(p.actual)}</span>`).join(' ')||'<span class="diff-empty">（空白）</span>';const original=parts.filter(p=>p.type!=='extra').map(p=>`<span class="diff-${p.type}"${p.type==='different'?` title="我的听写：${esc(p.actual)}"`:''}>${esc(p.expected)}</span>`).join(' ');return `<div class="dictation-comparison"><div><span class="comparison-label">我的听写</span><p>${mine}</p></div><div><span class="comparison-label">原文</span><p>${original}</p></div><div class="diff-legend"><span><i class="legend-correct"></i>正确</span><span><i class="legend-different"></i>不同</span><span><i class="legend-missing"></i>漏词</span><span><i class="legend-extra"></i>多词</span></div></div>`}
  function renderStudy(){
    const m=currentMaterial(),ss=currentSentences(),p=state.progress[m.id],s=ss[p.currentSentenceIndex],settings=state.settings,d=ensureDictation();
    setHead('SENTENCE LEARNING',m.title);
    const dictationBlock=`<section class="dictation-block" aria-labelledby="dictationTitle"><div class="dictation-head"><div><p class="eyebrow">FIRST DICTATION</p><h2 id="dictationTitle">第一遍听写</h2></div><span class="step-state">${d.submitted?'已完成':'先听后写'}</span></div><p class="dictation-instruction">听到什么就写什么，不确定的地方可以留空。</p><textarea id="dictationInput" rows="4" aria-label="第一遍听写" spellcheck="false" autocomplete="off" autocorrect="off" autocapitalize="off" placeholder="在这里输入听到的内容……" ${d.submitted||d.skipped?'readonly':''}>${esc(d.draftText)}</textarea><div class="dictation-actions"><button class="secondary-btn" id="replaySentence" type="button">重新播放</button><button class="primary-btn" id="submitDictation" type="button" ${d.submitted||d.skipped?'disabled':''}>${d.submitted?'已完成听写':'完成听写'}</button></div></section>`;
    let sentenceContent='<div class="blind-state"><div><strong>完成第一遍听写后再对照原文</strong><p>英文与中文当前保持隐藏。</p></div></div>';
    if(settings.showEnglish){sentenceContent=d.comparing&&!d.skipped?`${renderDiff(s.textEn)}${renderWords(s)}`:renderWords(s);sentenceContent+=`<div class="post-dictation-actions"><button class="secondary-btn" id="listenWithEnglish">▶ 看着英文再听一遍</button><button class="secondary-btn" id="retryDictation">重新默写</button></div>`}
    $('#app').innerHTML=`<section class="app-page"><div class="study-layout"><article class="panel study-card"><div class="player"><div class="source-line"><span>${esc(source(m))}</span><span>${p.currentSentenceIndex+1} / ${ss.length}</span></div><div class="play-row"><button id="playButton" class="play-main" aria-label="播放当前句">▶</button><input id="timeline" class="range" type="range" min="0" max="1000" value="0" aria-label="播放进度"><span id="timeLabel" class="time">00:00 / --:--</span></div><div class="controls"><label>播放速度<select id="speed"><option>.75</option><option selected>1</option><option>1.25</option><option>1.5</option></select></label><label>重复遍数<select id="repeat"><option>1</option><option>2</option><option>3</option><option>5</option></select></label><label>间隔秒数<input id="pause" type="number" min="0" max="10" step=".5" value="${settings.pauseSeconds}"></label><label>音频类型<input value="${s.startMs!=null?'原始音频 · LRC 完整句':'完整句子音频'}" disabled></label></div></div>${dictationBlock}<div class="toggles"><label class="toggle"><input id="showEnglish" type="checkbox" ${settings.showEnglish?'checked':''}> ${d.submitted&&!settings.showEnglish?'显示英文并对照':'显示英文'}</label><label class="toggle"><input id="showChinese" type="checkbox" ${settings.showChinese?'checked':''} ${!settings.showEnglish||!s.textZh?'disabled':''}> 显示中文</label><label class="toggle"><input id="highlight" type="checkbox" ${settings.highlightVocabulary?'checked':''}> 高亮词汇</label><label class="toggle"><input id="autoContinue" type="checkbox" ${settings.autoContinue?'checked':''}> 自动连续</label></div><div class="sentence-stage" id="sentenceStage">${sentenceContent}${settings.showEnglish&&settings.showChinese&&s.textZh?`<p class="sentence-zh">${esc(s.textZh)}</p>`:''}<div id="selectionMenu" aria-live="polite"></div></div><div class="sentence-nav"><button class="secondary-btn" id="prev" ${p.currentSentenceIndex===0?'disabled':''}>← 上一句</button><span class="meta">Sentence ${p.currentSentenceIndex+1} of ${ss.length}</span><button class="primary-btn" id="next" ${p.currentSentenceIndex===ss.length-1?'disabled':''}>下一句 →</button></div></article></div></section>`;
    bindStudy();
  }
  function durationMs(s){return Math.max(2200,s.textEn.length*75)}
  function formatMs(ms){const sec=Math.max(0,Math.round(ms/1000));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function renderWords(s){const occ=state.occurrences.filter(o=>o.sentenceId===s.id);return `<p class="sentence-en">${s.textEn.split(/(\s+)/).map((part,i)=>{if(/^\s+$/.test(part))return part;const clean=part.replace(/^[^A-Za-z]+|[^A-Za-z’'-]+$/g,''),start=s.textEn.split(/(\s+)/).slice(0,i).join('').length,end=start+part.length,isMarked=occ.some(o=>start<=o.tokenStart&&end>=o.tokenEnd);return `<button class="word" data-word="${esc(clean)}" data-start="${start}" data-end="${end}">${isMarked&&state.settings.highlightVocabulary?`<mark>${esc(part)}</mark>`:esc(part)}</button>`}).join('')}</p>`}
  function bindStudy(){
    const settings=state.settings,d=ensureDictation(),input=$('#dictationInput');
    $('#speed').value=String(settings.playbackRate);$('#repeat').value=String(settings.repeatCount);
    $('#playButton').onclick=()=>playing?stopAudio():startPlayback();$('#replaySentence').onclick=()=>startPlayback();
    $('#timeline').oninput=e=>seekCurrent(Number(e.target.value)/1000);
    $('#speed').onchange=e=>{settings.playbackRate=Number(e.target.value);audio.playbackRate=settings.playbackRate;save()};
    $('#repeat').onchange=e=>{settings.repeatCount=Number(e.target.value);save()};
    $('#pause').onchange=e=>{settings.pauseSeconds=Number(e.target.value);save()};
    $('#autoContinue').onchange=e=>{settings.autoContinue=e.target.checked;save()};
    $('#highlight').onchange=e=>{settings.highlightVocabulary=e.target.checked;save();renderStudy()};
    input.oninput=e=>{d.draftText=e.target.value;saveDictation()};
    input.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();completeDictation()}};
    $('#submitDictation').onclick=completeDictation;
    $('#showEnglish').onchange=e=>handleEnglishToggle(e.target.checked);
    $('#showChinese').onchange=e=>{settings.showChinese=e.target.checked;save();renderStudy()};
    $('#prev').onclick=()=>moveSentence(-1);$('#next').onclick=()=>moveSentence(1);
    const listenAgain=$('#listenWithEnglish');if(listenAgain)listenAgain.onclick=()=>{stopAudio();playSentence(currentSentence(),currentMaterial(),false)};
    const retry=$('#retryDictation');if(retry)retry.onclick=()=>{settings.showEnglish=false;settings.showChinese=false;resetDictation();save();renderStudy()};
    $$('.word').forEach(w=>w.onclick=()=>selectWord(w.dataset.word,Number(w.dataset.start),Number(w.dataset.end)));
  }
  function completeDictation(){const input=$('#dictationInput'),d=ensureDictation();d.draftText=input?.value||'';d.firstAttemptText=d.draftText;d.submitted=true;d.skipped=false;d.comparing=false;saveDictation();renderStudy();setTimeout(()=>$('#showEnglish')?.focus(),0)}
  function handleEnglishToggle(checked){const settings=state.settings,d=ensureDictation();if(!checked){settings.showEnglish=false;settings.showChinese=false;d.comparing=false;save();saveDictation();renderStudy();return}if(!d.submitted&&!d.skipped){const dialog=$('#skipDictationDialog');dialog.returnValue='';dialog.onclose=()=>{if(dialog.returnValue==='skip'){d.skipped=true;d.comparing=false;settings.showEnglish=true;saveDictation();save();renderStudy()}else{$('#showEnglish').checked=false;$('#dictationInput')?.focus()}};dialog.showModal();return}settings.showEnglish=true;d.comparing=d.submitted&&!d.skipped;saveDictation();save();renderStudy()}
  function selectWord(word,start,end){if(!word)return;activeSelection={word,start,end,sentenceId:currentSentence().id};const existing=state.vocabulary.find(v=>v.normalizedText===word.toLowerCase());const url=LONGMAN_BASE_URL+encodeURIComponent(word.trim().toLowerCase().replace(/\s+/g,'-'));$('#selectionMenu').innerHTML=`<div class="selection-menu"><strong>${esc(word)}</strong><div class="selection-actions"><a href="${url}" target="_blank" rel="noopener noreferrer">Longman Dictionary ↗</a><button class="primary-btn" id="addSelected">${existing?'Edit Definition':'Add to Vocabulary'}</button></div></div>`;$('#addSelected').onclick=()=>openVocabDialog(existing)}
  function openVocabDialog(existing=null){const s=existing?state.sentences.find(x=>x.id===existing.sourceSentenceId):currentSentence(),m=state.materials.find(x=>x.id===s.materialId);editVocabId=existing?.id||null;$('#vocabDialogTitle').textContent=existing?'Edit English Definition':'添加到生词本';$('#vocabText').value=existing?.displayText||activeSelection.word;$('#vocabDefinition').value=existing?.englishDefinition||'';$('#vocabSentence').textContent=s.textEn;$('#vocabSource').textContent=source(m);$('#vocabAudio').onclick=()=>playSentence(s,m);$('#vocabDialog').showModal();setTimeout(()=>$('#vocabDefinition').focus(),50)}
  $('#saveVocab').onclick=()=>{const def=$('#vocabDefinition').value.trim();if(!def){$('#vocabDefinition').reportValidity();return}if(editVocabId){state.vocabulary.find(v=>v.id===editVocabId).englishDefinition=def}else{const id=crypto.randomUUID();state.vocabulary.push({id,normalizedText:activeSelection.word.toLowerCase(),displayText:activeSelection.word,englishDefinition:def,sourceSentenceId:activeSelection.sentenceId});state.occurrences.push({id:crypto.randomUUID(),vocabularyItemId:id,sentenceId:activeSelection.sentenceId,tokenStart:activeSelection.start,tokenEnd:activeSelection.end})}save();$('#vocabDialog').close();toast(editVocabId?'释义已更新':'已加入生词本');if(location.hash==='#study')renderStudy();else renderVocabulary()};
  function startPlayback(){stopAudio(false);repeatRemaining=Number($('#repeat')?.value||settingsValue('repeatCount'));playSentence(currentSentence(),currentMaterial(),true)}
  function settingsValue(k){return state.settings[k]}
  function playSentence(s,m=currentMaterial(),loop=false){if(s.audioKind==='generated_reading_audio'||s.audioKind==='tts'){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s.textEn);u.lang='en-GB';u.rate=state.settings.playbackRate;u.onstart=()=>setPlaying(true);u.onend=()=>{setPlaying(false);if(loop)afterPlayback()};speechSynthesis.speak(u);return}audio.src=s.audioPath;audio.playbackRate=state.settings.playbackRate;const start=(s.startMs||0)/1000,end=s.endMs==null?null:s.endMs/1000;let finished=false;const finish=()=>{if(finished)return;finished=true;audio.pause();setPlaying(false);if(loop)afterPlayback()};audio.onloadedmetadata=()=>{audio.currentTime=start;updateAudioProgress();audio.play().then(()=>setPlaying(true)).catch(()=>toast('当前完整句子音频无法播放'))};audio.ontimeupdate=()=>{updateAudioProgress();if(end!=null&&audio.currentTime>=end)finish()};audio.onended=finish}
  function updateAudioProgress(){const s=currentSentence(),start=s.startMs||0,end=s.endMs==null?(audio.duration*1000):s.endMs,duration=Math.max(0,end-start),elapsed=Math.max(0,audio.currentTime*1000-start),ratio=duration?elapsed/duration:0,t=$('#timeline'),label=$('#timeLabel');if(t)t.value=Math.max(0,Math.min(1000,ratio*1000));if(label)label.textContent=`${formatMs(elapsed)} / ${duration?formatMs(duration):'--:--'}`}
  function afterPlayback(){repeatRemaining--;if(repeatRemaining>0){pauseTimer=setTimeout(()=>playSentence(currentSentence(),currentMaterial(),true),state.settings.pauseSeconds*1000)}else if(state.settings.autoContinue&&ensureDictation().submitted&&state.settings.showEnglish&&state.progress[currentMaterial().id].currentSentenceIndex<currentSentences().length-1){pauseTimer=setTimeout(()=>{moveSentence(1);setTimeout(startPlayback,60)},state.settings.pauseSeconds*1000)}}
  function setPlaying(v){playing=v;const b=$('#playButton');if(b){b.textContent=v?'Ⅱ':'▶';b.setAttribute('aria-label',v?'暂停当前句':'播放当前句')}}
  function stopAudio(update=true){clearTimeout(pauseTimer);cancelAnimationFrame(frame);audio.pause();speechSynthesis.cancel();setPlaying(false);if(update){const t=$('#timeline');if(t)t.value=0}}
  function seekCurrent(ratio){const s=currentSentence();if(s.audioKind==='original'&&audio.duration){const start=(s.startMs||0)/1000,end=s.endMs==null?audio.duration:s.endMs/1000;audio.currentTime=start+(end-start)*ratio}}
  function moveSentence(delta){stopAudio();const m=currentMaterial(),p=state.progress[m.id],max=currentSentences().length-1;p.currentSentenceIndex=Math.max(0,Math.min(max,p.currentSentenceIndex+delta));p.completedSentenceCount=Math.max(p.completedSentenceCount,p.currentSentenceIndex+1);state.settings.showEnglish=false;state.settings.showChinese=false;dictation=blankDictation(currentSentence().id);saveDictation();save();renderStudy()}
  function renderVocabulary(){setHead('VOCABULARY BOOK','生词本');$('#app').innerHTML=`<section class="app-page"><div class="section-head"><div><p class="eyebrow">ENGLISH DEFINITIONS ONLY</p><h2>${state.vocabulary.length} 个生词 / 短语</h2></div><div class="vocab-search"><span>⌕</span><input id="vocabSearch" type="search" placeholder="搜索 Word / Phrase"></div></div><div id="vocabList" class="vocab-list"></div></section>`;drawVocab('');$('#vocabSearch').oninput=e=>drawVocab(e.target.value)}
  function drawVocab(q){const list=state.vocabulary.filter(v=>v.displayText.toLowerCase().includes(q.toLowerCase()));$('#vocabList').innerHTML=list.length?list.map(v=>{const s=state.sentences.find(x=>x.id===v.sourceSentenceId),m=state.materials.find(x=>x.id===s.materialId),url=LONGMAN_BASE_URL+encodeURIComponent(v.normalizedText.replace(/\s+/g,'-'));return `<article class="panel vocab-item"><div class="vocab-item-head"><div><h3>${esc(v.displayText)}</h3><p class="definition">${esc(v.englishDefinition)}</p></div></div><div class="context"><p>${esc(s.textEn)}</p><span class="meta">${esc(source(m))}</span></div><div class="item-actions"><button class="secondary-btn play-vocab" data-id="${v.id}">▶ Original Sentence Audio</button><a class="file-btn" href="${url}" target="_blank" rel="noopener">Longman Dictionary ↗</a><button class="secondary-btn edit-vocab" data-id="${v.id}">Edit Definition</button><button class="danger-btn remove-vocab" data-id="${v.id}">Remove</button></div></article>`}).join(''):`<div class="panel empty-state"><h2>生词本还是空的</h2><p>在逐句学习页显示英文并点击单词，即可查询 Longman 并保存 English Definition。</p></div>`;$$('.play-vocab').forEach(b=>b.onclick=()=>{const v=state.vocabulary.find(x=>x.id===b.dataset.id),s=state.sentences.find(x=>x.id===v.sourceSentenceId);playSentence(s,state.materials.find(x=>x.id===s.materialId))});$$('.edit-vocab').forEach(b=>b.onclick=()=>openVocabDialog(state.vocabulary.find(x=>x.id===b.dataset.id)));$$('.remove-vocab').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.vocabulary=state.vocabulary.filter(v=>v.id!==id);state.occurrences=state.occurrences.filter(o=>o.vocabularyItemId!==id);save();drawVocab($('#vocabSearch').value);toast('已从生词本移除')})}
  $('#quickContinue').onclick=()=>{location.hash='study'};$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');window.addEventListener('hashchange',route);document.addEventListener('click',e=>{if(e.target.closest('.sidebar a')&&innerWidth<=900)$('.sidebar').classList.remove('open')});updateCount();route();
})();
